# CTD(SBE 911plus)를 이용한 해수 압력측정 표준운영절차서


## 기본 동작원리
SBE 911plus CTD는 미국 Sea-Bird Electronics 사에서 제작한 장비로 세계에서 가장 널리 사용되고 있으며, 특히 WOCE(World Ocean Circulation Experiments)의 표준장비로 사용되고 있다(Kim et al,2000). 이 장비는 바다 속에서 관측하는 부분인 SBE 9plus underwater unit (main housing, pump and sensors)와 CTD 제어, 자료수신, 전원공급을 하는 SBE 11 deck unit로 구성되어 있다. 특히, deck unit 부분에는 water sampler를 제어하는 button이 있어, 관측시에 원하는 수심에서 해수를 채수할 수 있다. 이 장비는 자료를 초당 24회의 속도로 획득한다. SBE 9plus의 구성은 그림 1과 같고 제원은 다음 표1과 같다.

이 장비는 수온과 전도도를 측정하기 위해서 SBE 5T 또는 SBE 5P 펌프를 이용하여 해수를 일정한 유속(30 ㎤/s)으로 직경 0.4 ㎝의 T-C duct 입구를 통해 온도센서와 전도도셀을 순차적으로 통과시킨다. 펌프를 사용하는 장점은 수중에서 CTD의 움직임과 상관없이 해수가 일정한 속도로 센서와 접촉할 수 있게 한다. 일단 해수가 T-C duct로 유입되면 수온이 즉시 감지되고 duct를 통해 해수가 흘러 0.073초후에 conductivity cell로 들어간다. 펌프의 속도가 고정되어 있기 때문에 온도센서와 전도도센서 사이의 지연시간(0.073초)은 항상 일정하고, SBE 11plus Deck Unit에서 실시간으로 자동 보정된다. 

## 장비구성
### 주요센서
#### 수온센서
수온센서의 측정원리는 수온이 변화할 때 저항(resistance)이 변하며, thermistor의 저항에 따라 주파수(즉, signal)이 달라지는 원리로 측정된다. 그러나, 따뜻한/고인 찬물에서 찬/따뜻한 물로 주변 환경이 바뀔 때, 따뜻한/찬 환경에 있을 때 존재한 thermistor 내부의 열이 찬/따뜻한 주변 환경으로 확산되는 데 시간이 필요하게 된다. 흔히 이러한 time constant(step change가 주어질 때, 센서가 최종값의 약 63%에 도달하는데 걸리는 시간)은 약 70ms(0.070초)로 알려져 있다. SBE9plus underwater unit의 경우에 24Hz, 즉 0.0417초마다 측정하므로 이에 대한 보정은 흔히 생략된다. 아래 표는 Sea bird 제조사에서 권장하는 장비별 전형적인 수온센서 배열시간이다. Data processing 프로그램의 Alignctd 과정에서 보정을 하게 된다.

#### 전기전도도 센서
전기전도도 센서의 셀은 약 2 cm3의 부피를 갖으며, 30 ㎖/s의 양으로 펌프의 작동에 의해 플러싱될 때 이러한 부피는 약 67ms의 시간이 소요된다. 전기전도도의 변화에 따른 셀의 time constant는 약 24ms(0.024s)로 알려져 있다. 그러나 이러한 전기전도도 셀의 특징에 의한 반응시간 보다는 아래의 그림처럼 전기전도도와 수온이 동시에 관측되지 않는 이유로 인한 두 센서간의 반응시간 차이가 중요하다. 전기전도도로부터 계산되는 염분은 수온, 전기전도도, 압력의 함수이기 때문에 정확한 염분계산을 위해서는 수온과 전기전도도의 동시 측정이 필요하다. 그러나 해수는 수온센서를 통과한 후에 전기전도도 센서를 통과하므로 이러한 차이를 보정하기 위한 과정이 필요하다. SBE11plus deck unit는 전기전도도와 수온센서간의 전형적인 시간차가 0.073 초이므로, primary 전기전도도 센서에 대하여 +1.75scans(24Hz에서 1.75/24=0.073 seconds) 만큼 factory-set를 하고 있지만, 주로 수온변화가 급격한 thermocline에서 매 관측시마다 차이(-0.08초~0.08초)를 보이므로 시간차에 대한 정확한 계산이 필요하다. 시간차에 대한 정확한 보정은 염분 값에 나타나는 튐 현상을 대부분 보정할 수 있다. 이 매뉴얼의 alignctd 과정에서 자세히 설명하기로 한다.

#### 압력센서
반도체 물질에서 압전저항 효과는 (piezoresistive effect) 결정구조의 변화에 의한 전기저항 변화를 브리지 회로를 통해 평가한다. 온도변형에 따라 저항변화가 일어나기 때문에 측정기가 동일한 저항을 가지게 하기 위해 동일한 기하 모양으로 배열하고 온도를 정밀하게 측정하여 보정해 주어야 한다. 반도체 물질에서 압전저항 효과는 금속변형율 측정기보다 약 50배 정도 더 민감하다. 압전저항 압력변환기는 일반적인 반도체 제조 방밥으로 수행하고 있고, 압력하에서 변형되는 탄성 멤브레인과 저항기를 하나의 칩에 통합할 수 있어 전체 압력 측정 셀이 한 개의 칩으로 구성되어 있어 아주 작은 크기로 만들 수 있다. SBE 9plus에 사용된 압력센서는 Paroscientific사의 Digiquartz 압력센서이다. 이 센서는 압력에의한 변형이 정밀한 수정결정 공명의 진동주기를 변화시키고, 진동주기 변화가 정밀시계 와 계수기에 사용되는 진동전자에 의해 측정된다. 

#### 용존산소 센서
해수 중 용존산소는 측정하는 SBE 43 센서는 아래 그림과 같이 해수가 센서의 membrane 표면으로 먼저 확산된 후, electrode를 덮고 있는 Teflon membrane을 통하여 확산되어진 후 electrode 위의 electrolyte로 확산되어 진다. 이때 electrode 표면에서 화학적인 반응이 발생하며, 이러한 확산율은 수온에 의존하게 되므로 센서의 반응시간은 수온의 함수이다. 일반적으로 20℃ 수온에서 time constant(τ)는 약 2초로 알려져 있으나, sensor와 membrane의 조건과 age에 따라 달라진다.

### 배열 방식
SBE 9plus는 기본적으로 수직 상태로 사용되지만 SBE 32 Carousel Water Sampler와 같이 사용할 때는 수평 상태로 사용된다. 수직배치(horizontal mount)와 수평배치(vertical mount)의 펌프 위치나 배관은 다르며, 펌프와 배관이 적절하게 배열되지 않으면 공기가 갇히거나 펌프가 잘 작동되지 않는 문제가 발생할 수 있다.

#### vertical mount
주 배관은 내경 13 mm, 외경 19 mm 인 Tygon관(이후 Tygon tubing)이다. 출수부의 높이가 입수부의 높이와 같도록 출수관을 틀에 부착한다. 출수부에서 빠져나온 물이 입수구로 유입되지 않도록 출수부의 위치는 가능한 한 입수부에서 멀리 떨어지게 한다. DO 센서의 입수부와 출수부에 길이가 13 mm인 내경 9.5 mm Tygon tubing을 끼우고 그 위에 더 큰 Tygon tubing(내경 13 mm)을 끼워 빡빡하게 맞도록 한다. DO 센서를 장착하지 않는 경우에는 conductivity cell과 Y-fitting을 바로 연결한다.

#### horizontal mount
주 배관은 내경 13 mm, 외경 19 mm인 Tygon tubing이다. DO 센서의 입수부가 conductivity 센서의 출수부 위에 오도록 한다. 펌프 입수부를 DO 센서 출수부 위에 오도록 한다. 펌프의 출수부는 위로 향하게 한다. DO 센서의 입수부와 출수부에 길이가 13 mm인 내경 9.5 mm Tygon tubing을 끼우고 그 위에 더 큰 Tygon tubing(내경 13 mm)을 끼워 빡빡하게 맞도록 한다. DO 센서를 포함하지 않는 경우에는 conductivity cell과 펌프 입수구를 바로 연결한다.

### 케이블 연결 방법
#### bottom end cap
SBE 9plus의 bottom end cap에는 흰색의 pressure port가 하나 있고 검은 색의 connector가 6개 있다(그림 4). pressure port부터 시계방향으로 primary temperature와 primary conductivity 센서를 연결하는 connecto(JB1, JB2), 펌프를 연결하는 connector(JB3), secondary temperature와 secondary conductivity 센서를 연결하는 connector(JB4, JB5)가 배치되어 있으며, 가운데에 SBE사에서 제조한 bottom contact switch가 있는 경우 연결할 수 있는 connector(JB6)가 배치되어 있다. temperature 센서와 conductivity 센서에는 pin이 3개(3-pin)인 연결부가 있으므로, 끝이 모두 3-pin인 cable(제품번호; 17086, 그림 6)을 센서의 연결부와 bottom end cap의 connector(JB1, JB2, JB4, JB5)에 꽂아 센서와 본체를 연결한다. JB3에 펌프를 연결할 때는 끝이 모두 2-pin인 cable(제품번호; 17133, 그림 7)을 사용하고, 펌프가 2개인 경우는 Y-cable(제품번호; 17799, 그림 8)을 사용한다.

#### top end cap
SBE 9plus의 top end cap에는 2-pin connector(JT1), 3-pin connector(JT4)와 5개의 6-pin connector(JT2. JT3, JT5, JT6, JT7)가 있다(그림 5). 2-pin connector에는 sea cable(제품번호; 17027, 17028, 17136 등, 그림 9)을 연결하고 전압을 이용하는 추가 센서들은 각 센서에 맞는 cable을 사용하여 JT2, JT3, JT5, JT6 connector에 연결한다. 참고로 DO 센서(SBE43)는 6-pin-4-pin cable(제품번호; 171491, 그림 10)를 이용한다. SBE32 Carousel water sampler를 이용하려면 가운데의 JT7 connector에 6-pin-6-pin cable(제품번호; 17198, 그림 11)을 사용하여 연결하고, General Oceanics사의 Rosette water sampler를 이용하려면 JT4에 3-pin-3-pin cable(제품번호; 17196, 17533 , 둘 중 normal polarity, reverse polarity에 따라 맞는 것을 선택)을 사용하여 연결한다.
※ SBE 9plus에는 2-pin connector가 3개(JT1, JB3, JB6) 있는데 JT1에 연결해야할 sea cable를 사용자가 실수로 JB6에 연결하여 CTD가 고장 나는 경우가 종종 있어 이를 방지하고자 2007년 2월 이후 생산된 SBE 9plus의 JB6는 삽입형(female)로 변경되었다. 그렇지만 여전히 펌프를 연결하는 JB3과 sea cable을 연결하는 JT1은 같은 돌출형(male) 2-pin connector이므로 잘못 연결하지 않도록 주의해야 한다.

## 운영절차
### 관측 전 SEASAVE 설정
항해를 시작하기 전에 seasave 프로그램을 이용하여 CTD와 컴퓨터의 연결 상태, GPS 자료 연계,  CTD의 각 센서의 정보 입력, 항해에 적합한 display 설정 등 작업을 수행한다. seasave를 실행하면 가장 최근에 사용된 setup 내용이 기본으로 이용되므로 필요한 경우 기존에 있는 적절한 program setup file (*.psa)를 불러오기를 한다(그림 12).

#### 기기 설정(Instrument Configuration) 변경 : seasave > configure inputs 
환경을 설정하는 configuration file을 만드는 과정으로 자료 취득 전에 가장 먼저 행해지는 과정이며, 자료 취득 후에도 post-calibration 과정에서 자료의 교정을 위해 행해지기도 한다.

① seasave를 실행한 후, configuration inputs 메뉴를 실행하여 Instrument configuration탭을 선택한 후(그림3-1), 기존의 파일(Open)이나 아니면 사용자가 임의의 파일(Create)을 선택한 다음(*.con), 'Modify' 메뉴에서 해당하는 화면에 따라 적절한 정보를 입력한다. ‘Create'를 선택하는 경우에, 다음 화면에서 '911/917plus CTD'를 선택하고,  
② "Frequency channels suppressed"에서 0,1,2중의 하나를 선택한다 (그림3-2). 선택에 따라 Frequency의 개수가 달라진다. 이것은 T, C 센서의 single/dual 부착과 관련되며, dual T, C라면 0을, dual T & single C센서라면 1을, single T, C센서라면 2를 선택한다. T, C 센서의 값은 frequency로 출력되기 때문에 (다른 부가적인 센서는 voltage로) 이 값은 T, C 센서와 관련된다.  
③ “Voltage words suppressed"는 0~4범위에서 선택되는데 (그림3-2), CTD underwater unit의 상부 커넥터에 부착하는 센서(DO, fluorometer, altimeter, nitrate sensor, turbidity-meter 등)과 관련된다. 이러한 센서는 커넥터의 JT2(V0, V1), JT3(V2, V3), JT5(V4, V5), JT6(V6, V7)에 모두 8개까지 부착가능한데(한개의 커넥터에 듀얼케이블을 사용하여 두개의 센서까지 부착가능하기 때문에 각 커넥터에 2개의 Voltage가 있다. 한개의 센서만을 한개의 커넥터에 케이블로 연결하는 경우가 일반적인데 이때 연결된 센서는 그 커넥터의 낮은 번호 voltage에 할당된다) (그림3-3), 이때 최대 voltage의 숫자에 따라 Voltage words suppressed의 숫자가 결정된다. 만일, JT6에 altimeter만이 연결되어 V6가 필요하게 되었다면, 0으로 설정하여 Voltage 7까지 유효하게 해주어야 한다. 0은 voltage 7번까지, 1은 voltage 5번까지, 2는 voltage 3번까지, 3은 voltage 1번까지, 4는 부가적인 센서가 부착되지 않는 경우에 선택해준다. 부가적인 센서를 부착하지 않더라도 4가 아닌 다른 숫자를 선택해주어도 무방하다.  
④ “Computer interface"에서 IEEE-448과 RS-232중에 하나를 선택한다. Deck unit와 computer간의 연결방법으로 대부분의 국내 조사선은 RS-232 방식을 사용한다.  
⑤ “Scans to average"에서 숫자를 입력한다. CTD의 full data를 얻기 위해서는 1을 선택해야하며, 만일 24Hz로 자료를 얻는 SBE911 CTD의 경우에 24를 입력하면, 1초당 1번의 자료만을 얻을 수 있다.  
⑥ “Surface PAR voltage added"는 underwater unit 상부 커넥터에 케이블로 연결하는 PAR 센서 외에 별도의 Surface PAR 센서를 부착하는 경우에 선택한다. 자세한 내용은 Application Note 11s를 참조하면 좋다.  
⑦ “NMEA position data added"는 NMEA 네비게이션 장치가 부착되었을 때 선택하며, 가능하면 반드시 NMEA 네비게이션 장치를 부착해주는 것이 좋다. Pressure에서 수심(m)를 계산할 때 기준위도가 필요한데, 만일 네비게이션 장치가 부착되지 않는 경우에는 매 정점마다 비교적 정확한 수심을 얻기 위해서는 configuration inputs 메뉴의 ”Miscellaneous" 메뉴에서 현재 관측점의 위도를 입력해주어야 한다.  
⑧ “Scan time added"는 data와 함께 각 scan마다 시간(GMT 1970년 1월 1일이래 경과된 초)을 포함하게 한다. 흔히 선택을 안한다.  
⑨ 이러한 위의 선택작업이 완료되면, 아래쪽의 해당하는 센서 혹은 Free를 더블 클릭하면서 새로운 센서를 목록에서 추가하거나 혹은 calibration sheet를 보면서 센서에 해당하는 계수를 주의 깊게 입력해준다. 이때 해당하는 센서가 목록에 없는 경우가 간혹 발생하는데, 이럴 경우에는 최신의 프로그램 버전을 재설치하면 대부분 해결된다. 표3-1에 주요 센서별 필요한 voltage로부터 계산식과 변수의 정의를 나타내었다.  
⑩ 모든 작업이 완료되면, Save 혹은 save as를 눌러 파일을 저장한다. 처음에 한번만 작업해놓으면 특별한 경우(센서의 변경 등)가 없으면 계속 사용할 수 있다.

#### 'Serial Ports'의 입력
① 케이블의 연결. Deck unit와 computer간의 통신케이블 연결은 그림 3-6의 deck unit 후면부의 (4)번 SBE11 interface (흔히 RS-232) (7)번 MODEM CHANNEL(water sampler 관련 케이블)에 Deck unit 케이블(그림 3-7) 각각 1개를 이용하여 컴퓨터와 연결한다. 흔히 컴퓨터에는 9pin 통신포트 대신에 2~3개의 USB 포트가 부착되어 있는데, 이를 위하여 미리 9pin 커넥터와 USB 포트를 연결하기 위한 USB용 케이블을 준비해야 한다. 그리고 deck unit 후면부의 (3)번에 전원케이블을 연결한다. CTD의 Deck unit와 underwater unit의 연결은 후면부의 (8)번에, 그리고 NMEA 연결은 (10)번에 연결한다.  
② 케이블 연결이 종료되면, <Configure input>메뉴의 <Serial ports> 탭에서 관련 port를 설정해야 한다 (그림 3-8). “CTD Serial port”에서는 deck unit의 후면부의 (4)번에서 연결된 com port 번호, Baud rate(9600 혹은 19200), data bits (8), parity (None)을 지정한다. “Water sampling port”에서는 deck unit의 후면부의 (7)번에서 연결된 com port 번호를 선택해준다. "Serial Data Output data port"는 <Configuration outputs>메뉴의 <Serial data output> 탭에 있는 “Output data to serial port"가 선택된 경우에 한해 유효하다. “SBE14 Remote display Serial Port"도 <Configuration outputs>메뉴의 <SBE14 Remote display> 탭에 있는 “Send data to SBE14 remote display"가 선택된 경우에 한해 유효하다.  
③ <Water sampler> 탭에서 water sampler 관련정보를 선택한다. "Water sampler type"에서는 흔히 사용되는 SBE carosel을 선택하고, "Number of Water Bottles"에서는 부착된 Niskin bottle의 총 개수가 아닌 Carosel water sampler 상단부의 trigger part에(그림 3-10) 연결되어져 있는 Bottle을 기준으로 trigger에 표시된 최대숫자를 입력해야 한다. 만일, bottle은 6개 이지만, trigger에 하나 걸러 하나씩 연결되었다면 최대숫자가 12가 되므로 12를 입력해주어야 한다. “Firing sequence"에서는 sequential/User input등이 있지만, Sequential로 선택하면 낮은 숫자부터 높은 숫자로 순서대로 bottle을 firing 하므로, 가능하면 User input을 입력해 때에 따라서 번호를 불규칙하게 firing을 해야 하는 경우에 대처하는 것이 좋다. “Enable remote firing"은 TCP/IP port를 통하여 조사선내의 원격 computer로부터 firing 하는 경우에 선택한다. 대부분 선택하지 않는다.  
④ <Miscellaneous> 탭은 Seasave 프로그램을 실행하면서 window에 display 되는 변수(depth, average sound velocity, descent rate, acceleration, oxygen, plume anomaly, and potential temperature anomaly)들의 계산시 필요한 정보를 입력하며,  이러한 입력정보는 관측후 자료처리과정과는 무관하다. “Latitude when NMEA is not available"에서 만일 NMEA navigation 케이블이 연결되지 않았을 때 관측정점의 위도를 입력해주어야 Seasave 하는 동안 pressure로부터 depth를 계산할 때 비교적 정확한 depth 정보를 얻을 수 있다. 만일 NMEA 케이블이 연결되었다면 필요하지 않다.  
⑤ 설정이 완료되면 ‘OK' 탭을 누르고 configuration file을 저장한다.

#### Water Sampler 설정
Configure Inputs를 클릭한 후 Water Sampler를 연다(그림 20). Water sampler type에서 SBE Carousel을 선택한다. Number of Water Bottles에 carousel에 달리는 총 bottle 수를 입력한다(24개를 달 수 있는 carousel에 20개의 bottle을 다는 경우도 24를 입력). Firing sequence에서 User Input을 선택한다(Sequential을 선택하는 경우 간혹 firing오류가 발생하면 몇 번 bottle까지 firing됐는지 확인이 어렵다)

#### 경고음 설정
Configure Outputs를 클릭한 후 SBE11plus Alarms를 연다(그림 21). altimeter가 장착되어 있는 경우 Enable altimeter alarm을 체크한다. Alarm set point(meters)에 경고음이 울리는 altimeter값을 입력한다.

#### 표시화면(Display) 설정
Window display 화면은 sea-save 프로그램의 <Display> 메뉴에서 창을 만들어준다. 그림 4-1처럼  크게 Fixed, Scrolled, Plot display 창으로 구성되며,  <Display> 메뉴를  통해 새로운 창을 만들어준다. 화면상에서 주의할 것은 비록 자료는 24Hz 혹은 8Hz 등으로 얻어지지만 각각의 옵션에서 업데이트 되는 시간(초)를 지정할 수 있음에 유의한다. 즉, 1초로 설정되어 있으면, 1초 마다의 자료가 display 화면에 업데이트 되고, 0으로 설정되어 있으면  모든 자료가 빠르게 업데이트 된다.

① Fixed display  
Fixed display는 해당되는 변수의 현재 값만을 표시하며(그림 4-1 그리고 4-2) 흔히 Scan number, Pressure(db), Depth(salt water, m), Temperature (ITS-90), Potential temperature(ITS-90), Salinity, Dissolved oxygen(ml/l 혹은 μmol/kg), altimeter 등 부착된 모든 센서의 정보와 함께, pump 정보가 선택될 수 있다. Fixed display의 변경은 오른쪽 마우스를 누르고 ‘Modify' 옵션을 선택하면 된다. ’Modify' 옵션에서는 각 변수의 소수점 이하 숫자수(pump의 경우에는 on/off), 텍스트의 색, 텍스트 바탕화면의 색을 지정할 수 있으며, Font의 size를 small/medium/large 등급에서 결정할 수 있으며, 새로운 변수를 추가하기 위해서는 오른쪽 해당 변수를 선택하고 ‘Add' (순서대로 추가), ’Insert'(기존의 변수들 사이에 삽입), ‘Change'(기존 변수를 새로운 변수로 교체)’ 버튼을 누르면 된다. 삭제하기 위해서는 상단의 ‘Delete' 버튼을 누른다. 상단의 “Seconds between updates" 옵션은 Fixed display에서 업데이트 되는 시간 간격을 결정한다. 이것은 자료의 저장간격과는 무관하다. 만일 0이면 모든 자료를, 1이면 1초 간격으로 자료를 업데이트 한다. 흔히 0으로 둔다. Fixed display에서  오른쪽 마우스를 누르고 ‘Export display setting' 옵션을 선택하면 지정한 화면을 파일로 저장해 두어 필요할 때 불러들일 수 있다.

② Scrolled display  
Scrolled display는 Fixed display와 다르게 선택된 각 변수들에 대해 vertical column 상에서 최근 얻어진 자료까지 보여준다(그림 4-3). 설정 방법은 Fixed display와 유사하다. Scrolled display의 변경은 오른쪽 마우스를 누르고 ‘Modify' 옵션을 선택하면 된다. "Rows to display"는 화면에서 동시에 보여줄 열(row)의 숫자(최대 40)이며, ’Total rows'는 표시할 전체 열의 숫자(최대 200)이다. 만일 Rows to display< Total rows 이면 화면에 scroll bar가 생기며,  Rows to display= Total rows 이면 scroll bar가 사라진다. 바닥근처까지 관측할 때 Altimeter 정보를 이 화면에서 표시하면 유용하다.  상단의 “Seconds between updates" 옵션은 ‘0’으로 지정하는 것이 좋다.

③ Plot display  
Plot display는 하나의 plot에 5개의 변수까지(1개 변수의 Y축과 4개 변수의 X축 혹은 1개 변수의 X축과 4개 변수의 Y축) 보여줄 수 있는 display이다. 필요한 경우(다른 스케일에서 보고자 하는 경우) 다수의 창을 만들 수 있다. ‘Plot Setup' 탭에서 환경을 설정한다 (그림 4-4). “Number of seconds between plot updates”에서 데이터의 업데이트 간격을 초단위로 입력하며 (가능하면 0을 입력하여 모든 데이터를 plot한다), “Plot type"에서 Single X-Multi Y 혹은 Single Y-Multi X(일반적)을 선택하며, ”Number of Axies"에서 plot할 변수축의 개수를 2~ 5개범위에서 설정하며, “Title"에서는 plot 의 title을 텍스트로 입력한다. ”Font size"에서 plot 되는 모든 텍스트의 크기를 small/medium/large 등급에서 설정한다.
 “Enable upcast line colors"를 선택하여 downcasting와 upcasting 할 때의 색이 구별되게 해주면 좋다. 각각의 색은 해당되는 축의 탭에서 선택하게 된다. 이때, ”Minimum pressure to determine upcast"와 “Pressure decrease to determine upcast"가 활성화 된다. 이것은  Minimum pressure to determine upcast에서 입력되는 pressure 보다 관측 pressure가 클때, 관측되는 pressure가 최대 pressure보다  ”Pressure decrease to determine upcast“에서 입력되는 값만큼 적을 때  upcast에 지정된 색이 나타남을 의미한다. 예로서 "Minimum ~"의 값을 300으로 하고, ”Pressure ~"를 30으로 설정하였다면,  CTD가 300 dbar 이상 하강하고, 이때 만일 최대 관측 pressure가 310 dbar라면 280 dbar 에 올라왔을 때 upcast line에 해당되는 색이 표시된다.
 ”Bottle display"의 "Show bottle lines"를 선택하면 plot에 firing 되는 bottle의 number와 line이 표시되어 편리하다. “Show fire sequence"를 선택하면 plot의 오른편에 순서대로 닫힌 bottle의 목록이 표시된다. 
“Mark line display"는 관측동안 특정 수심에서 특별한 현상이 있을 때 사용자가 이 수심의 다양한 센서 자료를 파일로 저장하고자 할 때 필요로 한다. 이를 위해서는 우선 상단의  ”Configure outputs"메뉴의 “Mark variables" 탭에서 저장하고자 하는 변수들을 지정해주고, 상단의 <Real-time control> 메뉴에서 ”Mark scan control"을  선택하여 이 메뉴를 활성화 주어야 한다. 관측동안 ”Mark scan control"의 창에서 특정 수심에서 “Mark scan"을 누르면 Mark line이 표시되고 이러한 자료들은 *.mrk 라는 파일로 저장된다.
“Redraw buffer size"는 buffer의 최대 scan 수이며, ”Queue size limit"는 queue의 최대 scan 수로, Sea-bird 사는 각각 4000, 10을 권장하고 있다.
“Grid line use"는 plot에 표시되는 가로 세로 grid의 유무를 설정하며 (Horizontal and Vertical을 권장), ”Grid line style"은 plot에 표시되는 grid의 line style을 지정(dotted Line을 권장) 하며, plotting 되는 data 위에 grid를 표시할 경우 “Grid in front"를 선택한다. 
각각의 변수들은 ‘Y-Axis' 등 각각의 탭에서 입력해주면 된다. 'X-Axis 1'의 탭에 potential temperature를 표시한 사례가 그림 4-5에 나타내었다. 그림에서 “Auto page this axis"을 선택하면, 변수의 구간을 벗어나는 경우에 변수의 범위만큼 자동적으로 새로운 화면으로 이동하게 된다. 이러한 기능은 새로운 화면으로 넘어갈 때 기존 plot이 보이지 않으므로 불편한 점이 있으나 특정 depth 구간을 변경하면서 자료를 보고자할 때 유용하다. 예컨대 2500m까지 관측하는 경우, 새로운 plot display를 만들어 Y-Axis을 depth로 하고 Auto page를 선택해 놓고 depth 범위를 0~500까지 지정해 놓고, X-Axis에는 descent rate와 altimeter를 지정해 놓으면, 500m 단위로 화면이 이동하면서 descent rate(CTD 상승.하강 속도), altimeter data(바닥근처에서만 작동하므로)를 보여주므로 유용하게 활용할 수 있다.  그림 4-6에 plot 되는 화면을 나타내었다. 이 창에서 오른쪽 마우스를 클릭하면 각 변수를 변경할 수 있으며, 파일로 저장도 가능하다. 

④ Bottle firing display  
Bottle firing을 control 하는 창으로, <Real-time Data> 메뉴에서 <Start>를 눌러 파일을 저장하기 시작하면 자동적으로 창이 활성화 된다. 만일 창이 활성화 되지 않는 경우에는 <Real-time control>메뉴의 <Fire bottle control>을 선택해준다. 원하는 수심에서 "Fire button"을 누르면 Bottle이 firing 된다. firing 되는 순서의 결정은 <Configuration input> 메뉴의 <Water sampler> 탭에서 지정해준다. 

> Bottle firing 시에 필요한 경우 특정 수심에서 여러 개의 bottle을 firing 하는 경우가 발생하는데, 이 때는 적절한 시간간격을 두어야 한다. Bottle firing 버튼을 누르면 Deck unit 전면부의 “Water sampler control" 의 오른쪽 버튼의 바로 왼쪽 LED가 on/off를 약 5초 동안 빠르게 반복하는데 이 동작이 마쳐지면 다음 bottle의 firing 작업을 수행하는 것이 좋다.

### 양질의 자료 획득을 위한 최적화
SBE 9plus는 하강속도(profiling rate) 0.5∼2 m/s로 최적화 되어 있다. 일반적으로 자료의 품질(data quality)과 연직 해상도(profile resolution)가 가장 잘 절충된 속도는 1 m/s이다. CTD 하강속도는 바다 상태(sea state)에 따른 선박의 움직임을 고려하여 조절한다. 바다가 거칠 때는 선박의 요동에 의한 turbulent wake 때문에 자료의 품질이 나빠질 수 있기 때문에 CTD 하강속도를 빠르게 한다. 바다가 매우 잔잔할 때는 CTD 하강속도를 느리게 하여 (예; 10∼20 cm/s) 연직 해상도를 높일 수도 있다. 
CTD는 하강할 때 T-C duct의 입구가 교란되지 않은 해수를 지나가도록 센서 배치가 되어 있기 때문에 downcast data가 upcast data보다 품질이 좋다. 양질의 자료를 위해서는 센서를 지나는 해수를 다른 장비가 열적으로 오염시키지 않도록 T-C duct 입구의 위치를 조절해야 한다. 
추운 겨울에 CTD가 선상에 노출되어 있거나 햇볕에 의해 뜨거워지는 등 CTD가 보관된 곳의 온도와 해수의 수온이 매우 다른 경우 CTD를 표층에 수 분(3∼4분)간 담궈(soak) 해수의 수온과 동일하게 해야 좋은 자료를 획득할 수 있다.
매우 거친 바다 상태에서는 선박의 움직임에 의해 CTD 하강이 멈추거나 오히려 상승하는 경우가 발생할 수 있다. 만약 winch 속도가 매우 높아 wire가 빨리 풀리거나 많이 풀려 있는 상황에서 CTD의 하강속도가 늦춰지면 kink가 발생할 수 있으며 특히 carousel이 조합된 상태라면 CTD만 있는 경우에 비해 drag가 더 커서 kink의 가능성이 더 높다. 100∼200 kg(경우에 따라 더 많은 중량)을 추가로 달면 drag 효과를 극복하는 데 도움이 된다.

### 정선 관측 절차
① 케이블 연결과 configuration file 설정이 완료되면, <Real-Time Data> 메뉴의 <Start>를 실행한다.   
② <Start>메뉴의 “Data Archiving Options"에서 Begin archiving data immediately (즉시 자료를 저장하는 경우), Begin archiving data when 'Start Archiving' command is sent (Real-time Date 메뉴의 Start-Archiving 메뉴를 누르기 전까지 자료를 저장하지 않음), Do not archive data for this cast (자료를 저장하지 않고 단지 real-time으로 자료를 display만 하는 경우) 중 하나를 선택한다. (그림 3-12)  
③ “Output data [.HEX] file"에서 저장할 디렉터리와 파일이름을 입력해준다. 만일 위에서 Do not archive data for this cast 이 선택되었다면 이 메뉴가 활성화되지 않는다.  
④ “Configuration Options"에서는 설정한 configuration 파일을 변경할 때 사용한다. Configuration input 메뉴에서 저장된 파일이 자동적으로 지정되어 있다. 따로 변경해줄 필요는 없다.  
⑤ “Timeout in seconds at startup" 메뉴는 장비로부터 첫 번째 scan의 data를 받기전에 경과되는 시간(초)를 입력하며, 만일 data가 이 시간 내에 장비로부터 받지 못하면 자료 획득을 시도하는 것을 중단하게 된다. 아래의 ‘Start' 버튼을 누르면 몇 초 동안 waiting 창이 자동적으로 새롭게 display되면서(그림 3-13) computer에 입력된 정보를 deck unit를 통하여 underwater unit 에 보내게 되는데, 여기에서 설정된 시간내에 정보소통이 원활하지 않으면 error 메시지가 뜨게 된다. 10 이상의 숫자를 입력해주는 것이 좋다.  
⑥ “Timeout in seconds between scans" 메뉴는 첫 번째 scan의 자료를 획득하고 난 후 scan들 사이의 허용된 최대 gap 시간(초)를 입력하며, 만일 scan들 사이에 이 시간 내에 자료를 얻지 못하면 seasave 프로그램은 중단되게 된다. 통상 10을 넣어주었다.  
⑦ 아래의 ‘Start' 버튼을 누른다. 누른 후에 때때로 “Header information"창이 새롭게 display 되는데, 사용자가 필요한 정보를 입력하고 ’Ok' 버튼을 누르면 된다. 이 정보는 자동으로 생성되는 ‘*.hdr'파일에 저장된다. 만일 ”Header information" 창을 원하지 않는 경우에는 <Configuration outputs> 메뉴의 <Header Form> 탭에서 “Don't include Header information in file"을 선택하고 저장하면 된다. ”Header information"의 format 또한 <Header Form> 탭에서 변경할 수 있다. 또한 “Data Archiving Options"에서 Begin archiving data when 'Start Archiving' command is sent를 선택한 경우에 주의를 알리는 새로운 창이 뜨기도 한다.  

> 주의사항 : ‘Start' 버튼을 누르기 전에 Deck unit가 power on 상태여야 하며, 자료가 다시 deck에 올라오면 ’Stop' 버튼을 누른 후에 Deck unit를 power off 시켜야 한다. 만일 ‘Stop' 버튼을 누르지 않고 먼저 Deck unit 버튼을 누르면 자료 저장이 원활하지 않을 수 있다.  

⑧ 모든 연결이 올바르면 window 화면에서 실시간으로 자료가  display 되면서 저장을 시작한다.  이때 만일 “Data Archiving Options"에서 Begin archiving data when 'Start Archiving' command is sent를 선택한 경우에, 실시간으로 자료가 display 되지만 상단의 <Real-time Data> 메뉴의 <Start Archiving>을 누르기 전까지 자료는 저장이 되지 않음에 주의한다. 이러한 경우를 방지하기 위해서 가능하면 “Data Archiving Options"에서 Begin archiving data immediately를 선택해 주는 것이 좋다.  
⑨ 정점 관측이 종료되면,  상단의 <Real-time Data> 메뉴의 <Stop> 메뉴를 실행하여 자료 저장을 종료시키고, Deck unit를 power off 한다. 저장되는 자료는 .hex 혹은 .dat 확장자로 자동저장된다. Rawdata의 확장자 이름은 SBE911plus CTD를 Seasave 6.0 버전 이상의 프로그램으로 실행하는 경우에  .dat 확장자로 저장되는 경우를 제외하고 모든 경우에 (SBE911plus CTD 외의 다른 CTD 혹은  SBE911plus CTD라도 Seasave 7.0 이상의 버전으로 실행되는 경우) .hex 파일로 저장된다.

### 관측후 절차
- CTD 전체를 깨끗한 물로 씻는다(그림 44).
- 0.1% Triton X-100 용액을 주사기에 넣고 주사기를 T-C duct inlet에 꼽은 후 수 회 왕복하여 0.1% Triton X-100 용액이 Conductivity cell을 청소하게 한다(그림 45). (※ 0.1% Triton X-100 용액에 DO 센서를 장기간 노출시키는 것은 센서의 막에 해로우며 센서 drift가 발생하게 된다. DO 센서의 기름기를 제거하기 위해 0.1% Triton X-100 용액을 사용하기는 하지만 표층에 기름이 많은 해역에서 관측하는 등 특별한 경우가 아니면 매 cast 후 마다 DO 센서를 0.1% Triton X-100으로 세척할 필요가 없다. DO 센서에 영향을 주지 않고 conductivity cell을 세척하기 위해서 conductivity cell의 유출구에 부착된 관(Tyhon tube, 그림 46의 A)을 제거하고 0.1% Triton X-100 용액을 왈칵 떠내려 보내야(flush) 하지만 매 cast 사이에 튜브를 제거하고 다시 장착하는 작업이 번거롭다. 그러므로 0.1% Triton X-100 용액이 DO 센서에 들어가지 않도록 0.1% Triton X-100 용액이 conductivity cell과 DO 센서를 연결한 관의 중간(A지점)까지 다다르도록 주사기를 밀고 당기는 과정을 수 회 되풀이 하여 flushing을 대신한다.)
- 다량의 증류수를 펌프의 유출구(Fi.g 46의 B)로 넣어 충분히 DO센서와 conductivity cell을 헹군다.( ※ conductivity cell을 충분히 헹구지 않으면 cell에 소금 결정이 생기며 이 소금 결정은 이후 CTD 사용 시 결정이 녹을 때까지 센서의 정확도에 영향을 미친다.) 
- 선상에서 에어로졸이나 스프레이 등에 의해 오염되는 것을 방지하기 위해 500-100 ppm의 표백용액을 넣은 Tygon관을 conductivity 센서의 양 끝에 꼽아 cell을 표백용액으로 채운다(그림 47). 하지만 관측에서 매번 이렇게 보관하는 것이 번거롭기 때문에 증류수(없으면 깨끗한 청수)를 주사기에 채워 T-C duct에 꼽고 주사기를 밀어 증류수로 cell을 채운다(그림 34의 좌측 그림 참고). (※ 추운 날씨로 인해 센서가 얼 가능성이 있는 경우에는 빈 주사기 등을 이용하여 공기를 불어 넣어(압축공기 사용 금지) cell안의 물기를 제거하고 Tygon관을 양 끝에 꼽아 둔다.)
- 정점간 이동 등 CTD를 선상에 두어야 할 때 DO 센서에 직사광선이 닿지 않도록 하며 서늘하고 습기가 있게 보관한다.

## 자료처리

### Data Conversion (DATCNV)
Rawdata(.hex 혹은 .dat)를 engineering unit의 .cnv 파일로 바꾸어주는 과정이며, 자료의 configuration 파일이 필요하다.  
① File setup 탭에서는 변환할 파일의 configuration 파일, rawdata의 디렉터리, 출력할 디렉터리를 지정한다. (그림 6-1). 출력할 디렉터리는 가능하면 rawdata의 디렉터리와 다르게 해준다. 같은 디렉터리가 되면 파일을 overwrite 하므로 불편함이 많다.  “Match Instrument configuration to input file"을 클릭하면 다수의 rawdata를 한번에 처리하는 경우에 각 rawdata에 해당하는 configuration 파일을 자동적으로 loading 한다. ”Input files"에서는 Select 버튼을 눌러 한 개의 파일 혹은 Shift key를 이용하여 다수의 파일을 동시에 선택할 수 있다.  
② Data setup 탭에서는 다양한 옵션을 지정해준다 (그림 6-2). “Process scans to end of file"에서는 선택을 하면 각 파일의 모든 scan에 대해 실행하며, 선택하지 않으면 실행할 scan number의 범위를 지정해 줄 수 있다. 흔히 이 옵션을 선택하여 모든 scan에 대해 실행한다. ”Output format"은 Ascii와 Binary 중 Ascii를 선택한다. Binary를 선택하면 용량은 감소하지만 파일의 이상 유무를 확인할 수 없어 불편하다. 
“Convert data from"은 Upcast and down cast를 선택한다. 필요한 경우, down cast를 선택할 수 있다. ”Create file types"에서는 Create both data and bottle file/Create convert data file only/Create bottle file only중 하나를 선택하는데, Create both data and bottle file 해주는 것이 좋다. 
“Source of scan range data"에서는 생성되는 bottle file의 data 정보를 어디에서 얻을 것인가를 선택하는 옵션으로 SBE911plus CTD와 SBE32 Carosel water sampler를 사용한 경우 Bottle log(*.bl)file을 선택해준다. Scan range offset와 Scan range duration의 값을 지정한다. Bottle summary 과정에서 수심, 수온, 염분 정보 등은 scan number에 의한 특정 시간 동안의 자료를 평균하게 되는데, Scan range offset은 평균이 시작되는 시점과 관련되며 bottle이 firing 전(-) 혹은 후(+)의 초(second)를 지정한다. scan range duration은 초(second)단위로 전체 평균기간을 지정한다. 예로서, scan range offset을 -2(초)로, scan range duration을 4(초)로 지정하였을 때, SBE911plus CTD는 24Hz로 측정하므로, bottle firing이 시작되기 전 48개의 자료부터 모두 96개의 scan number 자료를 평균함을 의미한다.

“Select Output Variables” 탭에서는 다음 과정에서 필요한 변수를 선택하는 과정으로, 꼭 필요한 변수들은 scan number, pressure(db), temperature, conductivity (salinity는 이후의 과정에서 얻는다), oxygen 등을 선택하며, dual sensor로 관측한 경우에는 temperature, conductivity에 대해 primary와 secondary를 모두 선택한다.  또한 다른 변수들은 부착한 센서에 맞게 변수들을 추가적으로 선택한다. temperature에서 [ITS-90]과 [IPTS-68] 선택항목이 있는데,

$T_{68}=1.00024\times T_{90}(-2 \sim 35 \celsius)$

의 관계가 있다. 여기에서 ITS-90(International Temperature Scale of 1990)은 1989년 국제도량형위원회에서 승인된 국제눈금으로, IPTS-68(International Practical Temperature Scale of 1968)을 대체하고 있다.
Oxygen에 대하여 최종적으로 oxygen를 계산할 때 필요한 변수들은 dissolved oxygen concentration(ml/l), temperature, pressure(db), salinity, oxygen saturation(ml/l), oxygen signal(volts) 이므로 이를 고려하여 변수를 지정해주는 것이 좋다. 

> Oxygen 값의 계산에서 SEASAVE 혹은 DATCNV에서 계산되는 방법과 DERIVE에서 계산되는 방법이 다름에 유의해야 한다. Oxygen 계산시 알고리듬은 시간에 대하여 Oxygen signal을 미분하는데, SEASAVE와 DATCNV에서는 주어진 window size에 걸쳐 signal을 시간에 대하여 backward 만으로 미분한다. 그러나 DERIVE에서는 주어진 window size에 걸쳐 시간에 대해 backward와 forward로 미분하는 centered window 방식을 취한다. 그러므로 DERIVE에서 더 정확한 Oxygen 값이 계산된다.

- Scan count - 필수
- Depth(salt meter, m) - 옵션 (Miscellaneous 탭에서 관측위도 입력 필요)
- Pressure(db) - 필수
- Temperature (ITS-90, oC) - 필수
- Conductivity (S/m 혹은 ) - 필수
- Salinity : 옵션 - bottle firing 정보 얻기 위해 혹은 최종값과 비교하기 위해
- Oxygen (ml/l) - 권고
- Oxygen Voltage (V) - 권고
- Oxygen (µmol/kg) : 옵션 - 최종값과 비교를 위해 유용
- Oxygen saturation (ml/l) - 권고
- 기타 추가된 센서 : 필수  

③ Miscellaneous 탭에서는 특별한 변수(depth, average sound velocity, descent rate, acceleration, oxygen, plume anomaly, and potential temperature anomaly) 계산을 위한 옵션를 입력한다 (그림 6-4). “Latitude when NMEA is not available"에는 Depth 혹은 Sound velocity 계산 시 필요한 위도 정보를 입력해준다. Oxygen 계산알고리듬은 시간에 대하여 Oxygen signal 값을 미분을 필요로 하는데 이때 필요한 window size를 지정한다.  

* plume anomaly = potential temperature (s, t, p, Reference Pressure) ― Theta-B ― Theta-Z / Salinity-Z * (salinity ― Salinity-B)  

* potential temperature anomaly = potential temperature - a0 - a1 x salinity or potential temperature - a0 - a1 x Sigma-theta (When you select potential temperature anomaly as a derived variable, SBE Data Processing prompts you to enter a0, a1, and the selection of salinity or sigma-theta.)  

④ 하단의 ‘Start process'을 실행하면 출력디렉터리에 *.cnv 파일이 생성된다.

### Wild Edit

자료중에 비정상적인 자료(bad data)를 badflag로 대체함으로서 다음 과정에서 계산에서 제외시키는 기능을 한다. Wildedit는 하나의 scan에서 하나의 변수가 badflag가 되더라도  같은 scan상에 있는 모든 변수가 동시에 badflag이 되지 않고 선택된 변수에만 적용된다.  그림의 경우에는 100개의 scan을 한 block으로 정하여 이 block의 평균과 표준편차를 계산한 후에, 어떤 scan의 값이 그 block 평균과 표준편차의 2배 이상 차이 날 때 그 scan을 제거하고, 다시 100개 scan의 block 중에서 평균과 표준편차를 계산하고 마찬가지로 어떤 scan의 값이 그 block 평균과 표준편차의 20배 이상 차이날 때 그 scan을 badflag로 표시하게 된다.  
Pass 1, Pass 2, Per Block을 각각 2, 20, 100이 권장되지만, 자료에 따라 다른 값을 설정하는 것이 좋으며, 자료의 질이 좋지 않는 경우에는 위의 값을 변화시켜가며  WILDEDIT 과정을 여러 번 반복하는 것이 좋다. "Keep data within this distance of the mean"은 자료 값이 비록 위의 지정된 표준편차를 넘어서더라도 만일 평균으로부터 지정된 값 범위내에 있으면 자료를 badflag하지 않는 경우에 사용된다.  
만일, 두 개의 센서의 range가 크게 차이가 난다면 (예로서 센서 A의 range는 1000, 센서 B의 range는 10) Keep data within this distance of the mean을 다르게 하면서 wild edit를 여러 번 수행하는 것이 좋다. 예를 들어 센서 A의 range는 1000, 센서 B의 range는 10 의 경우, Keep data within this distance of the mean을 10으로 하여 센서 A에 대해 wild edit를 수행하고 Keep data within this distance of the mean을 0.1로 하여 센서 B에 대해 wild edit를 수행한다.

### FILTER
현장에서 관측할 때 흔히 CTD는 일정하게 내려가는 것이 아니라, 배의 Pitching(앞뒤로 흔들림), Rolling(옆으로 기울림)에 따라 내려가다 서다를 반복하는 등 불규칙적인 모습을 보여, 마치 CTD가 계단 형태로 내려가는 과정을 보여준다. 
CTD 하강속도에 따른 bad data를 취급하는 이후의 LOOP EDIT 과정에서 이러한 계단 형태의 자료는 마치 CTD가 멈춘 것처럼 해석되어 bad data로 간주되므로 이런 문제를 해결하기 위하여 미리 FILTER 과정에서 pressure (depth)에 대하여 low pass filter를 해줌으로서 문제를 해결한다.
SBE 911plus의 경우(24Hz로 자료취득)에는 0.15 초의 Low pass filter를 적용하고, SBE 25의 경우(8Hz로 자료취득)에는 0.5초의 Low pass filter를 적용하는 것이 권장되고 있다.
Data Setup > Specify Filters 옵션에서 pressure에 대해서만, 적용할 필터를 선택한다.

### ALIGNCTD

염분, 용존산소 등의 값은 고유의 값으로 측정되는 값이 아니라 압력, 수온 등의 함수로 간접적으로 계산되는 값이다. 즉, 염분은 압력, 수온, 전기전도도의 함수로 계산된다. 그러므로 정확한 염분 계산을 위해서는 압력, 수온, 전기전도도가 동시에 측정되어야 한다. 그런데, 아래 그림처럼 센서 설치의 구조적인 이유로 수온과 전기전도도 센서에 도달하는 해수의 도달시간이 달라 약간의 시간차를 가지고 수온과 전기전도도가 측정된다. 이러한 문제의 원인은 각 센서 자체의 반응시간 혹은 profiling speed의 차이에 의해서도 발생한다. 이러한 문제는 thermocline 등 수온이 급격하게 변화하는 층에서 특히 증가되며, 이처럼 수온센서와 전기전도도 센서 사이의 불일치는 염분 스파이크(salinity spike)로 알려져 있다.

이러한 염분 스파이크를 제거하기 위하여 수온센서와 전기전도도 센서의 시간차(time lag)를 조절하게 되는데, 이때 압력을 기준으로 각각의 센서에서 나온 모든 자료를 특정시간 만큼 앞/뒤로 움직여 보정한다.
이를 위하여 조정할 시간을 결정해야 하는데, 흔히 두가지 방법이 사용된다. 1) 자료에 대하여 다양한 시간을 alignctd에 대입하여 나온 결과를 SEAPLOT를 이용하여 salinity의 그래프를 확인하며 어느 시간에 가장 spike가 적은가를 판단하는 방법이다. 2) 프로그램화 시켜 수온과 전기전도도 자료를 high pass filter시킨 후(SBE 911plus의 경우 1cps의 cuf-off frequency filter를 사용한다. Kim, 1996) 수온과 전기전도도가 서로 어느 시간에 correlation이 가장 높은가를 얻는 방법이다. 즉, 염분 스파이크가 있으면 correlation이 낮게 나타난다는 것을 고려한 방법으로 수온이 연직적으로 변화가 큰 수온약층 근처의 자료만을 선택하는 것이 좋다.(동해의 경우 약 300m 이내).
SBE 25의 경우에는 Seabird 사에서 2000rpm pump에 대하여 전기전도도 센서를 온도센서에 대하여 0.1 sec로 앞당기라고 권장하고 있지만, 위의 방법에 의한 test 과정이 필요하다.

### CELLTM

CTD 센서가 hot water에서 cold water로 이동할 때, 전기전도도 센서 내부에 저장된 열이 sampling 되는 해수로 확산하게 되어 결과적으로 sampling water의 온도를 미약하게 상승시키게 된다. 이러한 현상은 free-stream value 상태에서 측정된 전기전도도 보다 높은 전기전도도를 얻게 한다. 결과적으로 유도된 염분은 원래의 값보다 높아지게 된다. 이러한 현상은 thermal-lag effect (센서에 남아있는 열 때문에 발생하는 효과)로 불려진다. (Morison et al., 1994, J. Atmos. Oceanic. Technol., 11, 1151-1164). CTD 관측시에 흔히 볼 수 있는 downcasting과 upcasting 사이의 상대적으로 큰 염분차이는 이러한 thermal-lag effect가 주요한 원인으로 알려져 있다. 이러한 현상은 수온약층처럼 수온이 급격하는 층에서 보다 명확해진다.
자료처리 알고리즘은 적절한 Thermal anomaly amplitude(alpha)와 Thermal anomaly time constant(1/beta)를 결정하여 thermal-lag effect를 보정해준다. Sea-bird사는 아래 표에서처럼 SBE 9plus Underwater unit의 경우 각각 0.03, 7.0 그리고 SBE 25의 경우에는 각각 0.04, 8.0을 권장하고 있다. 그러나 김영규 박사(1996, 서울대학교 해양학과 박사학위 논문)는 동해의 경우 1994년 여름과 1995년 여름 관측자료를 이용하여 SBE 9plus의 권장값을 검토해본 결과, 각각 0.018, 9.0이 보다 적절하다는 결론을 얻은 바 있으며, 또한 경험적으로 보았을 때 매번 Cruise 마다 적절한 값이 변화함을 볼 수 있다. Lueck (1990, Thermal Inertia of Conductivity Cells: Theory., American Meteorological Society Oct 1990, 741-755)는 alpha와 beta를 결정하는 방법을 제시한 바가 있었다.

참고로, Conductivity[S/m]는 아래의 식으로 계산된다.

$Conductivity = (g + hf^2 + if^3 + jf^4)/[10(1+ \delta t + \varepsilon p)] ~~~~ Siemens/meter$

여기에서 는 configuration 파일에서 미리 정해주는 변수인데, 특히, δ는 bluk compressibility를 의미하여, ε는 cell의 열팽창계수를 나타낸다. 그리고 f는 instrument frequency(Hz), t는 temperature(℃), p는 pressure(decibars)를 나타낸다.

### SECTION
CTD를 바다에 투입한 후 약 2~3 분 동안 수심 약 5~10m에서 센서가 적당한 값을 얻거나 혹은 pump가 제대로 작동하도록 흔히 대기하게 되며, 이 과정 후에 다시 표층으로 올려 관측을 시작하게 된다. 또한 CTD가 다시 상승관측을 하고 난 후 갑판으로 장비를 올려 해수를 벗어날 때도 사용자의 여건에 따라서 여전히 CTD는 자료를 획득하는 경우가 있다. 이처럼 센서의 조절을 위한 관측이나 수면을 벗어날 때의 관측 자료를 제거해야 올바른 자료를 획득할 수 있으므로 SECTION 과정에서 이러한 자료를 제거한다.
Variable을 흔히 scan number로 선택하고, 미리 SEASAVE를 통해 기록한 scan number를 기입해준다. 물론 이 과정 전에 SEASAVE를 통해 자료를 plot 하는 과정이 필요하다. 다른 과정은 특별한 경우를 제외하고 대부분 한번의 cruise 동안의 모든 파일을 동시에 처리할 수 있지만, Section 과정은 각 파일마다 각기 다른 scan number를 선택해주어야 하므로 시간이 소요되는 과정이다. 

### LOOPEDIT
CTD 자료는 CTD가 계속 일정한 속도로 내려가는 경우에 좋으며, 선박의 움직임 등에 의해 상하운동을 반복하는 자료는 질이 좋지 않다. Loopedit는 이런 자료를 제거하기 위한 과정으로 Fixed Minimum velocity 혹은 Percent of mean speed를 기준으로 자료를 badflag로 지정함으로서 계산과정에서 제거하게 된다. 흔히 Fixed Minimum velocity을 기준으로 최소 0.25 m/s가 권장되고 있다. 보통 CTD 관측 속도는 1m/s로 하강 혹은 상승이 권장되고 있다. 주의할 것은 Loopedit를 실행하기에 앞서 pressure sensor의 noise로 인한 효과를 제거하기 위해 Filter 단계를 먼저 실행하는 것이 권장되고 있다.
또한 Loopedit는 CTD가 해수에 입수한 직후 표층대기시간 동안의 자료를 badflag로 지정함으로서 이후 계산과정에서 제거할 수 있다. Remove surface soak 옵션을 선택하고,  아래의 그림처럼 적절한 Surface soak depth, minimum soak depth, maximum soak depth를 지정하면 된다. “Exclude scans marked bad"는 Loopedit 이전의 계산단계에서 badflag로 지정된 scan을 계산과정에 포함시킬지 아니면 skip할지를 결정한다.

### DERIVE
pressure, temperature, conductivity를 이용하여 salinity나 density, potential temperature를 계산하는 과정으로, density, potential temperature 등은 자료처리 과정이 모두 끝난 뒤에 계산하는 것이 권장된다. 왜냐하면, WFILTER 과정에서 salinity가 재처리되므로 이 과정이 끝난 후에 density(수온, 염분, 압력의 함수)를 계산하는 것이 필요하기 때문이다. 
Derive에서 계산되는 변수들은  
- density (density, sigma-theta, sigma-1, sigma-2, sigma-4, sigma-t)  
- thermosteric anomaly  
- specific volume  
- specific volume anomaly  
- geopotential anomaly  
- dynamic meters  
- depth (salt water, fresh water)  
- salinity  
- sound velocity (Chen-Millero, DelGrosso, Wilson)  
- average sound velocity  
- potential temperature (reference pressure = 0.0 decibars)  
- potential temperature anomaly  
- specific conductivity  
- derivative variables (descent rate and acceleration) - if input file has not been averaged into pressure or depth bins  
- oxygen (if input file contains pressure, temperature, and either conductivity or salinity, and has not been averaged into pressure or depth bins) - also requires oxygen current and oxygen temperature (for SBE 13 or 23) or oxygen signal (for SBE 43)  
- corrected irradiance (CPAR) 이다.

여기에서는 salinity, oxygen을 포함시키는 것이 권장된다. 또한 datcnv과정처럼 .con 파일이 필요로 한다. 여러 파일을 동시에 처리하는 경우에는 .con 파일을 입력 디렉터리에 미리 복사해두어야 한다. Derive에서 유도되는 변수들은 출력 디렉터리에 생성되는 파일Miscellaneous 탭에서는 특별한 변수(depth, average sound velocity, descent rate, acceleration, oxygen, plume anomaly, and potential temperature anomaly) 계산을 위한 옵션를 입력한다. “Latitude when NMEA is not available"에는 Depth 혹은 Sound velocity 계산시 필요한 위도 정보를 입력해준다. Oxygen 계산알고리듬은 시간에 대하여 Oxygen signal 값을 미분을 필요로 하는데 이때 필요한 window size를 지정한다.  

>Oxygen 값의 계산에서 SEASAVE 혹은 DATCNV에서 계산되는 방법과 DERIVE에서 계산되는 방법이 다름에 유의해야 한다. Oxygen 계산시 알고리듬은 시간에 대하여 Oxygen signal을 미분하는데, SEASAVE와 DATCNV에서는 주어진 window size에 걸쳐 signal을 시간에 대하여 backward 만으로 미분한다. 그러나 DERIVE에서는 주어진 window size에 걸쳐 시간에 대해 backward와 forward로 미분하는 centered window 방식을 취한다. 그러므로 DERIVE에서 더 정확한 Oxygen 값이 계산된다.

### WFILTER

이전의 자료처리과정에서 여전히 남아있는 자료(특히, 염분)의 spike를 제거하는 과정으로, window filter(4종류)와 median filter를 사용하여 자료를 smoothing 시킨다. 
이 과정은 다른 물리량에도 적용가능하나, 자료의 질이 굳이 적용될 정도가 아니므로 보통 salinity 자료에만 적용되며, spike를 제거하는데 가장 유용한 median filter가 흔히 사용된다. SBE 911plus 자료의 경우 초당 24개의 자료가 획득되며, 최종적인 자료는 보통 1m 간격의 자료를 사용하므로(하강속도는 1m/s 정도), 자료의 성격이 바뀌는 것을 방지하기 위하여 window size를 25개로 선택(window size는 홀수로 선택된다)하는 것이 권장된다. 여기에서 주의해야 할 것은 기존의 Datcnv에서 선택된 변수 외에 Derive에서 추가적으로 동일한 변수를 계산하였다면, Derive에서 계산된 변수에 대하여 wfilter를 적용해야 한다 (아래 그림에서 salinity 처럼).

### BINAVG

Binavg과정은 pressure, depth, scan number, time에 의해 자료를 일정한 간격으로 평균하는 과정이다. Include surface bin 옵션은 pressure 혹은 depth에 의해 자료가 일정한 간격으로 평균될 때 surface bin에 대한 계산 방법을 결정한다. 만일 Include surface bin이 지정되지 않고, bin size가 10 db이라면, 그림 A처럼 평균된다. 그러나 Include surface bin이 지정되고, surface bin minimum value =0, surface bin maximum vale=3, surface bin vale=0 이라면, 그림 B처럼 target bin, 즉, surface bin value에 대해 추가적인 계산이 가능하다. 1 db 간격으로 평균된다면 생략해도 괜찮다.

### ASCIIOUT

Asciiout 과정은 최종적인 Software 과정으로, 앞서 처리에 사용된 변수 중에 사용자가 원하는 변수들만을 출력시키는데 사용된다. Options 메뉴에서 Output data file을 체크하고, Exclude scans marked bad를 체크하여 이전의 처리과정에서 badflag로 처리된 부분을 최종 자료에서 제외시키고, Label columns에서 “Top of the file"을 선택하여 각 file의 맨 위 행에 column label를 붙여주는 것이 좋다. 특히, ”Select Output Variables..." 옵션을 선택하여, 원하는 변수를 클릭하면 되는데 이때 Derive과정에서 변수를 추가한 경우에는 이 변수를 최종 변수로 선택하는 것이 권장된다.
Asciiout의 출력파일 예. Binavg에서 1 db 간격으로 평균하였다. 맨 위쪽 행에 column label이 출력되었다.

※ Bottle firing 정보의 추출  
화학 및 생물팀에서는 채수한 수심에서의 정확한 수심, 수온(in-situ temperature), 염분, 밀도 정보 등을 필요로 한다. bottle firing은 두가지 방법으로 이루어지는데 1) Deck unit 후면부의 Modem channel을 통해 SBE32 water sampler가 연결되었을 때 window program 상에서 수행되거나 2) modem channel을 통해 sampler가 연결되지 않는 상태에서 deck unit 전면부의 fire button을 누름으로서 가능하다. 첫 번째의 경우로 firing이 되는 경우에만 SBE Data processing 프로그램의 Data conversion과 Bottle summary 절차를 실행함으로서 채수한 수심에서의 수심, 수온, 염분 정보를 얻을 수 있다. 그러나 두 번째의 경우에는 그러한 정보가 파일에 기록되지 않는다.

**<채수 정보의 추출 순서>**  
1.Data conversion을 실행한다.  
2.File setup 메뉴에서 해당하는 con 파일과 data 파일을 불러들이고, 출력할 디렉터리를 지정한다. 이때 data 파일과 con 파일은 같은 디렉터리에 있어야 한다.  
3. Data setup 메뉴에서 Output format : Ascii out, Convert from data : Upcast and downcast, Create file types : Create file (.ROS) file only, Source of scan range data : Bottle log (.BL) file를 선택한다.  
4. Scan range offset와 Scan range duration의 값을 지정한다. Bottle summary 과정에서 수심, 수온, 염분 정보 등은 scan number에 의한 특정 시간 동안의 자료를 평균하게 되는데, Scan range offset은 평균이 시작되는 시점과 관련되며 bottle이 firing 전(-) 혹은 후(+)의 초(second)를 지정한다. scan range duration은 초(second)단위로 전체 평균기간을 지정한다. 예로서, scan range offset을 -2(초)로, scan range duration을 4(초)로 지정하였을 때, SBE911plus CTD는 24Hz로 측정하므로, bottle firing이 시작되기 전 48개의 자료부터 모두 96개의 scan number 자료를 평균함을 의미한다.  
5. Select output variables 버튼을 클릭 하여 scan number, depth, pressure, temperature, salinity 및 부착된 센서의 변수를 포함한다.  
6. Start process 버튼을 눌러 실행한다. (*.ros 파일이 생성된다)  
7. Bottle summary를 실행한다.  
8. File setup 메뉴에서 해당하는 con 파일과 data 파일을 불러들이고, 출력할 디렉터리를 지정한다. 이때 data 파일과 con 파일은 같은 디렉터리에 있어야 한다.  
9. Data setup 메뉴에서 Output min/max values for averaged data의 on/off,  Select averages variables에서 출력할 변수의 지정(Data conversion 과정에서 지정한 변수만 선택된다), Select derives variables에서 추가로 출력할 변수를 지정한다.  
10. Start process 버튼을 눌러 실행한다. (*.btl 파일이 생성된다)

## 관리

### 데이터 관리
CTD 관측 데이터는 반드시 백업을 포함하여 2벌 이상 복사하여야 한다. 휴대용 저장장치에 데이터를 복사한 후 이동하는 경우 분실을 방지하기 위하여 동일 데이터를 두 사람이상이 소지한다. 

### 기록물 관리
야장 원본은 보관함이 원칙이다. 야장 분실을 방지하고 데이터 이용시 참조를 위하여 야장의 내용을 파일로 기록하여 데이터와 함께 보관한다.

### 장비 관리
관측 종료후 CTD를 깨끗하게 세척하고(7.4 참조) 보관한다. CTD 본체를 winch에서 분리하여 CTD 상자에 보관한다. T-C duct에 꼽은 Tygon관을 분리하고 sensor의 물기가 완전히 제거된 상태로 보관한다. 탐사장비 책임자는 의무적으로 탐사전후의 장비의 상태 및 문제점, 필요한 예비부품이나 소모품 등에 대해 정확히 기록하여야 한다.

### 주요 점검

#### 펌프 작동 점검 

SBE는 공기중에서 펌프가 작동되는 것을 방지하기 위해 염분 약 8psu 이하에서는 작동하지 않도록 제작되어 있다. 펌프의 작동 여부를 육상에서 테스트하기 위해서는 주사기를 통해 10psu 이상의 물을 T sensor에 주입한 후에, 펌프 케이블을 연결한 상태에서 펌프를 SBE 본체에서 분리하여 물통에 펌프를 담가놓는다. 펌프가 정상적으로 작동하는 경우에 다량의 물이(콸콸 솟아 나올 정도로) 펌프 유출구를 통해 배출되어 나온다. 펌프가 정상적으로 작동하지 않은 경우에도 Window program에서 펌프가 on 상태로 표시될 수 있어서, 반드시 펌프의 유출구를 통해 다량의 물이 솟아 나오는지를 확인해야 한다. 

#### Sea cable과 winch wire의 연결

▲ wire의 제원 (직경 8.05mm의 경우)
CTD 본체의 sea-cable과 wire(8.05mm)의 연결 작업이 수행되었다. 납땜으로 두 개의 선을 연결한 후, 고무 재질의 속이 비어 있는 보조라인을 라이터로 불을 쏘이며 녹이면서 signal과 ground선의 합선을 방지하기 위해 signal 납땜 부위를 덧 씌어준다 (이 보조라인은 납땜 전에 미리 끼워두어야 한다). 연결은 sea cable PIN 2와 wire 중간의 signal 선끼리, sea cable의 PIN 1과 wire 외부의 1~2개의 armor끼리 연결한다. 연결 후에 수압에 따른 누수 현상을 방지하기 위해 3M사의 고무테이프(Scotch 23, Rubber Splicing Tape, 자기 융착성 고무테이프)로 2~3회 감아준 후, 다시 절연테이프로 접촉부위를 감아주었다. 이때 접촉부위의 휨을 방지하기 위해 보조막대를 대주는 것이 좋다. 이번 조사에서 초기에 절연 테이프 만으로 감아주는 경우에 약 50미터 깊이에서 누수로 인한 자료 에러가 발생하는 현상이 발생하여 다시 고무테이프로 감아준 결과 이러한 에러 발생이 나타나지 않았다. 연결 전후에 드럼에 감겨 있는 와이어 끝단의 signal 선끼리 voltmeter로 저항을 측정하여 허용된 저항 이상치(예. 9.8 Ohm/km)가 나오면 (이상적으로는 저항이 0이어야 하지만)) 와이어의 누수를 의심해야 한다. 이러한 경우에 자료의 튐 현상이 발생한다.
winch가 감겨 있는 drum에는 Slip ring이라고 하는 전기기계적 장치가 있다. slip ring은 drum에서 회전하는 sea cable과 실험실에 있는 SBE11plus deck unit로 연결하는 케이블 사이를 연결하는 커넥터 역할을 한다. Slip ring의 한쪽 편은 sea cable의 내부 커넥터와 sea cable의 armor에 연결되며, 다른 한쪽 편은 SBE 11plus deck unit에 연결된다.

#### Conductivity 센서의 cleaning

전기전도도 센서의 셀은 주로 유리(glass)로 구성된 제품으로 쉽게 깨어질 수 있는 제품이다. 이러한 셀에는 관측 후에 셀 표면에 salt crystal이 부착되어 관측시에 이 salt crystal이 녹을 때까지 센서의 정확도에 영향을 미치게 되므로 Seabird 제작사는 관측후에 센서의 cleaning 작업을 권장하고 있다. 세척작업에는 0.1%의 Triton X-100 용액이 필요하다. 세척전에 만일 SBE43 DO센서가 부착되어 있다면 DO 센서의 membrane과 Triton이 접촉하는 것을 방지하기 위해(Triton은 membrane에 손상을 미칠 수 있다) tube의 연결을 분리하는 것이 필요하다. 0.1% Triton X-100용액을 주사기에 넣고 주사기의 물을 왕복시키면서 1분 이상 동안 세척작업을 실시한다. 세척작업이 완료된 이후에 청수로 용액을 완전히 씻겨준 후 물기를 빼내는 작업이 필요하다. 이번 조사에서는 두 대의 주사기(한대는 용액, 한대는 청수)를 사용하여 이러한 작업을 3~4차례 실시하였다. 이러한 세척작업 결과 염분의 튐 현상이 눈에 띄게 줄어드는 결과를 가져왔다.

#### DO 센서값이 튀는 문제 해결

DO 센서값이 튀는 현상은 센서를 수중으로 내릴 때 공기방울의 영향으로 발생하는데 DO센서를 올바르게 부착하는 것으로 줄일 수 있다. CTD를 옆으로 눕히는 horizontal mount의 경우에 아래 그림처럼 설치되어야 한다. 즉, DO 센서의 유입구는 염분을 측정하는 전기전도 센서의 유출구 위에 설치되어야 하며, DO센서의 유입구 위 약 45도 방향으로 DO센서의 유출구를 배치시킨 후 그 위에 펌프의 유입구를 두어야 한다. 펌프의 유출구는 약 45도로 기울여 설치해야 한다. 또한 DO 센서의 유입구 및 유출구에는 내부 직경 9.5mm, 길이 12mm의 Tygon tubing위로 내부 직경 13mm의 Tygon tubing을 설치하도록 한다.

#### Underwater bulkhead connector 연결

Bulkhead connector는 100% 실리콘 그리스를 엷게 발라(light coating) 매끄럽게 되게 한다. 실리콘 그리스는 윤활제 및 밀폐제 역할을 하므로 실리콘 그리스를 바르는 것이 꼭 필요하다. cable을 커넥터로 연결할 때 흔히 연결부분 내부에 공기가 들어가는 경우가 발생한다. 공기의 유입을 방지하기 위해서는 커넥터를 연결할 때 커넥터 아래쪽으로 손가락을 이용하여 힘껏 밀어 공기를 뺀다. 커넥터에는 WD-40 같은 수나사와 암나사 사이의 흡착을 방해하는 윤활제의 사용을 피해야 한다. WD-40 같은 윤활제는 connector의 고무 부분과 underwater unit의 금속 부분 사이에서 봉인을 녹이거나 분리하게 하여 장비의 누수를 불러일으킬 수 있다.
만일, 연결부분에 공기가 포함되어 있으면 심층으로 장비를 내릴수록 bulkhead와 케이블 사이의 공기가 압축되고 틈새로 해수가 연결부분 안쪽으로 스며들게 된다. 이때 power와 ground 사이에 수많은 통로가 존재하기 때문에, pin이 빠르게 침식된다. 만일 이러한 일이 진행되면, sensor 값이 noisy를 일으키거나 측정에 실패하게 되며, 혹은 장비를 작동하기에 필요한 main power를 얻을 수가 없다. 침식된 부분을 깨끗하게 청소한 후 사용할 수 있지만 가능하면 바로 pin을 교체하는 것을 권고한다.

#### 결빙환경에서의 센서의 보호

겨울철 관측 같은 결빙환경의 경우에 센서(특히 전기전도도)의 보호를 위한 조치가 필요하다. 전기전도도 센서는 주로 유리로 되어 있어 셀에 있는 물이 얼 때 깨어질 수 있다. 전기전도도 센서의 전극(electrode)에 반복된 얼음 부착은 0.001-0.020 psu 범위에서 calibration를 저하시킬 수 있다. 그러므로 갑판에 CTD가 있을때 전기전도도 센서 셀 내부의 모든 물을 제거해야 한다. 그리고 0.5 μm로 필터된 해수 또는 끓인 해수에 1% Triton 용액으로 채워주거나 혹은 센서를 분리하여 실험실내에 보관해야 한다. 이때 글리콜이나 알코올 같은 부동 용액을 사용해서는 안 된다. 

## 품질 관리와 품질 보증

자료의 정확도를 높이 위해서는 탐사전이나 탐사후에 센서를 calibration해야 한다. 현실적으로 매번 calibration 하는 것이 어려운 경우라면 되도록 자주 calibration을 해서 센서의 drift를 보정해야 한다.

## 참고문헌

SBE 9plus CTD User’s Manual, Version 13  
SBE Application Note 2D, "Instructions for Care and Cleaning of Conductivity Cells", 2008  
SBE Application Note 38, "Fundamentals of the T-C Duct and Pump-Controlled Flow Used on Sea-Bird CTDs", 1992  
SEASOFT V2:Seasave V7, "CTD Real-Time Data Acquisition Software for Windows 2000 and later" User's Manual, 2010  
SEASOFT V2: "SBE Data Processing CTD Data Processing and Plotting Software for Windows 2000/XP" User's Manual, 2009  
McTaggart, K. E., G. C. Johnson, M. C. Johnson, F. M. Delahoyde, and J. H. Swift, 2010; Notes on ctd/o2 data acquisition and processing using sea-bird hardware and software, IOCCP Report No. 14 











