# 용존산소 분석 표준운영절차서

## 목적 및 범위

해수시료의 용존산소 측정은 해수에 녹아 있는 산소가 아이오다이드 이온(I^-^)을 트리아이오다이드(I^3-^)로 정량적으로 산화시킨 후 발생된 트리아이오다이드(I^3-^)를 티오황산염 용액으로 적정하여 화학적으로 정량화하는 Winkler(1888) 적정법을 기초로 Carpenter(1965)가 변경한 적정법을 사용한다. 이 표준운영절차서는 해양수산부의 해양환경공정시행법 (2013-230)에 기초하고 있으며, 종말점 결정에 전기화학적인 방법의 적용, 분광광도법의 적용방법이 추가되어 있다.

## 측정 원리

일정량의 해수시료에 염화망간(MnCl~2~)을 첨가한 다음 곧 바로 알카리아오다이드화나트륨(NaOH/NaI)을 첨가하면 강한 알카리 환경에서 망간이온(Mn^2+^)은 수산화망간(Mn(OH)~2~)으로 침전한다(식1). 이때 수산화망간은 해수시료속에 용존되어 있는 용존산소와 반응하여 수화된 4가의 망간산화물(MnO(OH)~2~)의 갈색 침전물을 형성한다(식2). 시료병에 황산을 첨가하여 강한 산성환경을 만들어주면 갈색 침전물인 수화된 4가의 망간산화물(MnO(OH)~2~)이 산화제로 작용하여 시료속에 첨가된 아오다이드이온(I^-^)을 아이오딘(I~2~)으로 산화시킨다(식3). 이렇게 생성된 아이오딘(I~2~)은 시료에 과잉으로 존재하는 아오다이드이온(I^-^)과 결합하여 트리아이오다이드 착물(I^3-^)을 형성한다(식4). 생성된 트리아이오다이드 착물을 티오황산나트륨 용액으로 정량하여 해수시료속에 존재하고 있는 용존산소 농도를 계산한다. 티오황산염은 트리아이오다이드 착물(I^3-^)을 아이오다이드이온(I^-^)으로 환원시키는 역할을 한다. 생성된 트라이아이오다이드 착물(I^3-^)을 아이오다이드이온(I^-^)으로 완전히 환원시키는데 사용된 티오황산염량은 생성된 트리아이오다이드 착물(I^3-^)량의 두배이다(식5). 종말점을 정밀하게 확인하기 위해서 적정이 완료되기 직전에 녹말용액을 첨가하면 아직 아이오다이드이온(I^-^)로 환원되지 않고 남아 있는 트리아이오다이드 착물(I^3-^)과 반응하여 푸른색을 띤다(식6). 푸른색이 사라지면 시료속의 트리아이오다이드 착물(I^3-^)이 완전히 아이오다이드이온(I^-^)으로 환원되었음를 의미한다. 그리고 2몰의 티오황산염이 1몰의 트리아이오다이드 착물(I^3-^)을 환원시키므로 이때까지 사용된 티오황산염의 1/2몰이 시료속의 존재했던 트리아이오다이드 착물(I^3-^)의 몰수이고, 이는 수환된 4간의 망간산화물(MnO(OH)~2~)에서 생성된 1몰의 아이오딘(I~2~)에 해당한다. 해수시료속의 용존산소(O~2~) 1몰은 2몰의 아이오딘(I~2~)을 생성하므로 1몰의 아이오딘(I~2~)은 해수시료의 용존산소(O~2~) 1/2몰에 해당한다. 따라서 해수시료중의 용존산소(O~2~)는 트리아이오다이드 착물(I^3-^)을 아다이드이온(I^-^)으로 환원시키는 소비된 티오황산염량에 4를 곱하여 계산할 수 있다.

(1) $Mn^{2+} + 2OH^{-} → Mn(OH)_{2}$\
(2) $2Mn(OH)_{2} + O_{2} → 2MnO(OH)_{2}$\
(3) $2Mn(OH)_{2} + 6H^{+} + 2I^{-} → 2Mn^{2+} + I_{2} + 6H_{2}O$\
(4) $I_{2} +I^{-} = I^{3-}$\
(5) $I^{3-} +{2S_{2}O_{3}}^{2-} → 3I^{-} +{S_{4}O_{6}}^{2-}$\
(6) 녹말 + $I^{3-}$ → 푸른색

이 방법으로 측정가능한 해수중 용존산소 법위는 0-400 μmol kg^-1^이다. 이 방법의 정확도는 0.1% 미만 또는 ±0.3 μmol kg^-1^이다.

## 방해물

이 분석법은 **황화수소가 포함된 해수시료 분석**에는 부적합하다.

## 기구 및 기기

해수중 용존산소 분석에 필요한 기구 및 기기는 크게 시료채취기구(4.1), 적정기구(4.2)등이 있다. 실험에 사용되는 초자류를 10%의 염산으로 세척한 후 초순수로 3회 헹구어 사용한다.

## 시료채취 기구

### 시료병

시료병의 목부분이 가늘어 아오다인의 증기가 빠져나가기 어렵게 되어 있으며 젓빚유리 마개를 가지 125 ml정도의 Pyrex병을 사용한다. 시료병과 두껑은 한쌍으로만 사용하고 부피보정을 실시한다. 병의 부피는 ±0.003 ml 정밀도로 측정한다.

### 시약분주기/시약병

정밀분주기 3개가 필요하다. 시약1(MnCl2), 시약2(NaI/NaOH), 시약3(Sulphuric Acid)용 분주기 3개는 1.0 ml를 ±0.02 ml정밀도로 분주할 수 있어야 한다. 시약2(NaI/NaOH)용 분주기는 유리에 붙기 때문에 항상 주의를 기울여야 하고, 장기간 사용하지 않을 때 완전히 세척/분해하여 보관한다. 시약병은 장기간의 항해기간동안 햇빛의 영향을 방지하기 위해 차광병 사용을 권장한다. 시약1(MnCl2)과 시약2(NaI/NaOH)용 시약병은 실험실과 시료채취장소에 반복적으로 옮겨 다녀야 하기 때문에 두 시약병을 운반하는 상자를 사용하는 것이 편리하다. 시약병은 사각형모양을 사용할 것을 권장한다.

### 시료채취튜브

시료채취기(Niskin bottle)에서 시료병으로 시료를 옮길 때 투명하고 튜브벽의 두께가 얇아 휘기쉬운 플라스틱 튜브(Tygon tube)를 사용한다. 튜브의 직경은 시료병에서 시료를 흘러넘치게 할 때 적당한 속도가 될수 있을 정도의 직경이어야 한다. 휘기쉬운 실리콘 튜브를 짧게 잘라 Tygon tube 끝에 연결하여 시료채취 튜브를 니스킨병의 시료채취 꼭지에 연결하는데 편리하다. 시료채취 튜브를 사용하지 않을 때는 초순수에 보관한다. 시료채취전에 가볍게 만져 튜브 내부를 충분히 적셔주어 시료채취시 공기방울이 튜브 내부에 갇히는 것을 방지한다.

### 전자온도계

시료채취시 시료채취 튜브와 함께 시료채취병에 넣어 시료의 온도를 0.1 oC단위로 측정할 수 있는 전자온도계를 사용한다. 이때 측정된 온도는 시료채취시 해수의 밀도를 계산하는데 사용하고 자료처리과정에서 용존산소 농도단위를 μmol L-1에서 μmol kg-1로 변환하는데 사용한다. 또한 이 온도는 시료가 목표 수심에서 채취된 것인지 판단하는데 유용한 지표이다.

### 정밀저울

저울용량은 300g이고 정밀도가 0.001g인 전자저울을 사용한다.

## 적정기구

### 적정조정장치

자동적정을 위해서 티오황산염을 분주하기 위한 전동뷰렛과 종말점을 흡광도, 전류, 전위차로 감지하는 장치와 컴퓨터를 연결하는 조정장치로 구성되어 있다.

### 뷰렛

티오황산염을 미량으로 정밀하게 분주할 수 있는 1 ml, 2 ml, 또는 5 ml 수동 또는 전동뷰렛을 사용한다. 정밀한 적정을 위해 가급적 유리뷰렛 대신 정밀한 자동뷰렛을 사용하도록 한다.(예; Metrohm사의 665 Dosimat burette, SCHOTT Instruments사의 TITRONICⓡ universal)

### 초정밀 분주기

바탕용액이나 표준용액열을 제조하기 위해서 요오드산칼륨(KIO3)을 1.0 ml 와 10.0 ml를 정밀하게 옮길 때 사용하는 초정밀 분주기이다. SOCOREX Calibrex 520 bottle-top 분주기가 이러한 목적에 적합하다. 이 분주기는 1-11 ml까지 0.25 ml간격으로 증가시킬 수 있다. 분주기는 자주 사용하는 부피에 대해서 주기적으로 보정하여야 하고 재현성은 ±0.002-0.005 ml이다. 이목적에 적합한 다른 분주기는 MetrohmTM 피스톤 뷰렛이다.

### 자석교반기

25mm 테프론 코팅 자석교반막대기와 자석교반기가 필요하다.

### 스퀴즈병

250 ml 용량정도의 플라스틱병으로 초순수를 담아 눌러서 소량 배출하여 적정시 세척에 사용된다.

## 시약제조

용존산소 분석에 사용되는 시약은 염화망간(5.1), 알칼리 요오드화나트륨용액(5.2), 황산용액(5.3), 녹말지시약(5.4), 티오황산나트륨(5.5). 요오드화칼륨(5.6)등이 있다.

### 3M 염화망간(MnCl~2~·4H~2~O)용액

염화망간(MnCl~2~·4H~2~O) 600 g을 초순수 500-700 ml가 담긴 눈금이 있는 비이커에 넣어 잘 저어 녹인후 실험실 온도까지 식힌 후 초순수로 최종부피를 1000 mL로 맞추어 제작한다. 공경이 큰 유리섬유 여과지로 여과하여 혹시 있을 수 있는 입자물질을 제거한 후 플라스틱 용기에 넣어 보관한다. 시간이 촉박할 경우 자석교반막대와 자석교반기를 사용하여 제작하면 시간을 단축할수 있다. 시약제조시 안전도구(글러브, 고글)을 착용하고 퓸후드에서 제작해야 한다. 염화망간 대신 황산망간(MnSO~4~·4H~2~O) 480 g을 초순수에 녹여 최종부피를 1000 ml로 맞추어 사용해도 된다.

### 알칼리 요오드화나트륨(NaI/NaOH) 용액

수산화나트륨(NaOH) 320 g을 초순수 500 ml가 담긴 눈금이 있는 비이커에 녹인후 냉각시킨다. 필요에 따라서는 찬물이 담긴 통에 비이커를 넣어 빨리 냉각시킬 수 있다. 냉각이된 비이커에 요오드화나트륨(NaI) 600 g을 천천히 첨가하여 녹인후 냉각시키다. 시료중에 아질산질소가 많이 포함되어 있으면 아질산질소의 방해를 제거하기 위해 아자이드화나트륨(NaN~3~) 10 g을 첨가하여 녹인다. 실험실 온도로 충분히 식힌후 초순수를 첨가하여 1000 ml로 맞춘다. 이 시약은 공경이 큰 유리섬유 여과지로 여과하여 입자물질을 제거한 후 차광용기에 보관하여 햇빛에 의한 변질을 최소화해야 한다. 시약제조시 안전도구(글러브, 고글)을 착용하고 퓸후드에서 제작해야 한다.

### 50% (v/v) 황산용액(H~2~SO~4~)

진한 황산(H~2~SO~4~) 50 mL를 초순수에 1:1의 비율(초순수 50 ml에 진한 황산 50 ml를 첨가)로 혼합한다. 반드시 초순수를 먼저 정량플라스크에 담은 후 진한 황산 50 ml를 천천히 열을 식혀가면서 첨가하여야 한다. 실온으로 냉가한 다음 정량플라스크에서 100 mL 눈금까지 맞춘다. 시약제조시 안전도구(글러브, 고글)을 착용하고 퓸후드에서 제작해야 한다. 시약제조시 폭발의 위험성이 있으므로 초순수에 진한 황산을 첨가하는 순서를 반드시 지켜야 하고, 황산을 첨가할 때 천천히 하여야 한다.

### 1% 녹말지시약

수용성 녹말 1 g을 초순수 50 mL에 혼합한 다음 용액이 투명해질 때까지 가열하여 완전히 녹인 다음 초순수를 첨가하여 정확히 100 mL로 맞춘다. 그리고 이 용액은 상온으로 냉각하여 사용한다. 냉장보관이 가능하나 1주일을 초과하지 않아야 하며, 만약 장기간 보관하여야 할 경우에는 포화 염화수은(Hg~2~I~2~)을 소량 첨가하여 보관한다.

### 0.025 N 티오황산나트륨(Na~2~S~2~O~3~·5H~2~O) 용액

티오황산나트륨(Na~2~S~2~O~3~·5H~2~O) 약 6.205 g을 취하여 일정량의 초순수에 녹인후 정확하게 1000 mL로 맞춘다. 하지만 티오황산나트륨 용액의 농도는 분석하려는 시료의 용존산소 농도를 적정하기에 충분할 정도로 제조되어야 한다. 그리고 적정에 사용되는 뷰렛의 부피도 고려하여야 한다. 만약 시료의 용존산소 농도가 최대 400 μmol kg^-1^정도이고 적정에 사용되는 티오황산나트륨의 부피를 최대 2 ml이하로 하려고 한다면 티오황산나트륨 용액의 적정농도는 다음과 같이 구한다.

$$4 \times (C_{1} \times V_{1}) = C_{2} \times V_{2}$$\
여기서,\
$C_{1}: [O_{2}]=400 \mu mol L^{-1}$\
$V_{1}:$ 용존산소 시료병 부피 (10% 추가) $=14ml$\
$C_{2}: [Na_{2}S_{2}O_{3}]$\
$V_{1}:$ 뷰렛부피 (2ml)\
4:1 몰 산소($O_{2}$)적정에 4몰 $Na_{2}S_{2}O_{3}$ 소비\
따라서,\
$[Na_{2}S_{2}O_{3}]=\frac{400 \mu mol ~ L^{-1} \times 140ml \times 4}{2ml} \simeq 0.11M$\
$[Na~2~S~2~O~3~]=400 * 10^-6^ * 140 * 4 / Burette volume (2 ml) = 0.11M$

티오황산나트륨(Na~2~S~2~O~3~·5H~2~O) 1몰은 248.17 g이므로 약 27.4 g을 녹여서 1000 ml로 맞추면 된다. 만약 무수티오황산나트륨(Na2S2O3)을 사용할 경우 1몰이 158.09 g이므로 약 17.4 g을 사용한다. 이유는 확실하지 않으나 시약제조후 2-5일동안 보관후 사용하면 바탕값과 검량선값의 일일 변화가 적어 시간을 절약할 수 있으며 1L 이상 만들어 사용하기를 추천한다.

### 0.001667 M 요오드산칼륨 표준용액(KIO~3~,0.0100 N)

요오드산칼륨 (KIO~3~) 약 0.5 g을 120℃에서 약 2시간 동안 건조시킨 후 데시케이터에서 방냉한다. 요오드산칼륨 0.3567g을 정확히 취하여 초순수에 녹여 정확히 1000 mL로 한다. 실험실 온도(tp)를 측정하여 기록한다. 측정된 용존산소 농도의 정확도는 이시약을 얼마나 정확하게 만드느냐에 절대적으로 영향을 받는다. 본 시약은 티오황산염의 표준화에 사용되어지므로 정확히 0.3567g을 취하지 못할 경우, 측정 되어진 무게 값으로부터 몰 농도를 정확하게 구하여 티오황산염 용액의 표준화에 사용하도록 한다.

$$M (몰농도) =\frac{1L에 첨가되어진 요오드산칼륨 무게}{요오드산칼륨 분자량(214.0g)}$$

## 시료채취

## 시료채취 개요

채수기로부터 용존산소 분석을 위한 시료의 채취는 시료채취기가 표면에 도착후 가능한 짧은 시간내에 이루어 져야 한다. 수심이 깊은 곳에서 채수된 시료는 채수시간이 오래되었기 때문에 깊은 수심에서 표층으로 이동하는 동안 압력과 온도변화의 영향이 크기 때문에 시료채취를 먼저 해야 한다. 이는 표층에 대기하는 동안 온도가 상승하여 해수에 용존된 기체가 빠져나와 용존산소의 손실이 있을 수 있기 때문이다. 기체 시료 분석에 사용되는 시료 채취순서는 빈공간의 영향정도, 시료수가 적거나, 분석비용이 비싸거나, 분석에 노력이 많이 들어가는 순서로 하는 경우가 일반적이다. 일반적으로 사용되는 기체 시료채취 순서는 CFCs, Helium, Noble gases(aragon and zenon), O^17^, Oxygen, and pCO~2~순이다.

## 시료채취절차

1.  시료병과 뚜껑이 일치하도록 준비한다.
2.  시료채취시 사용하는 고정시약이 위험하니 조심해서 취급해야 하므로 보호장구(글러브와 고글) 착용을 권장한다.
3.  시료병을 반쯤 채워 헹구는 것을 두 번 반복하여 이전에 사용한 시약 잔류물을 완전히 제거한 후 시료를 흘러 넘치게한다.
4.  시료를 시료채취병에 채수할 때 시료채취 튜브를 시료병의 바닥까지 담군다음 시료를 천천히 채워 와류 또는 공기방울 생성을 최소화시킨다. 시료튜브를 눌러서 시료의 흐름을 줄여서 시료채취 튜브내의 공기방울 생성을 최소화한다. 그리고 시료채취를 시작할 때 시료병을 약 45도로 기울이고 시료가 차오르면 점진적으로 수직으로 세우면 시료채취시 공기방울 형성을 줄일 수 있다. 시료병을 채우는 데 걸리는 시간의 2-3배 정도 시료를 흘러넘치게 한 후 시료병 끝까지 채운다. 아직 시료병의 뚜껑을 닫지 않는다.
5.  시료를 채우고 흘러넘치는 동안에 전자온도계를 시료병에 담구어 시료채취시 온도를 측정한다. 이때 측정된 온도는 시료채취시 시료중 용존산소가 고정되는 시점의 해수시료 밀도를 결정하는데 사용한다. 그리고 수층에서 시료채취기가 채수할 때 기록된 현장 CTD온도보다 높을 수 있다.
6.  시료병에 채수가 완료되면 고정시약이 있는 곳으로 바로 이동하여 고정시약 염화망간 1 ml를 주입하고 이어서 알칼리 요오드화나트륨 용액 1 ml를 주입하고 뚜껑을 닫고 90초간 잘 흔들어 준다. 고정시약을 분주할 때 분주기 끝부분을 깊숙이 넣고 시약을 천천히 주입한다. 이는 시약이 너무 많이 혼합되지 않고 시료병의 바닥에 도달하도록 하여 병 입구 쪽에서 반응이 일어나는 것을 최소화해야 한다. NaI/NaOH 용액은 끈적거리기 때문에 분주기를 끝까지 올려 멈춰서 시약이 완전히 분주 되도록 해야 하고 주기적으로 분주기를 해체하여 씻어주어야 한다.
7.  시료병의 뚜껑을 닫을 때 공기방울이 갇히지 않도록 주의해야 한다. 첨가된 고정시약 2 ml에 해당하는 시료가 뚜껑을 닫을 때 유실되는데 계산시 이를 고려한다.
8.  엄지로 뚜껑을 잘 고정하여 손목을 사용하여 시료병을 위아래로 뒤집어 흔들어 시료와 시약을 잘 혼합한다.
9.  시약과 시료를 완전히 혼합한 후 뚜껑과 병목사이에 있는 빈 공간에 스퀴즈병에 있는 초순수를 채워 공기의 출입이 차단되도록 밀봉한다. 이 과정은 따뜻한 시료가 건조하고 시원한 연구선 실내에 보관되면 수축하여 시료병 내부로 외부의 공기가 들어갈 수 있는 틈이 생길 수 있는데 이를 차단하기 위해서이다.
10. 시약을 혼합한 후 약 30분이 지나면 한 번 더 시료병을 흔들어 시료병에 있는 모든 산소가 고정시약과 반응한 것을 확인한다. 그리고 초순수로 뚜껑을 다시 밀봉해야 한다.
11. 시료병을 보통 1시간 30분에서 2시간 동안 실험실 온도로 맞춘 후 분석한다. 그러나 사정이 여의치 않으면 뚜껑의 밀봉이 유지되면 수일 동안 보관하였다가 분석하여도 뚜렷한 용존산소 농도 변화가 없다.

## 시험방법

## 시약바탕측정

1.  시료병에 초순수를 반쯤 채우고 교반 자석 막대를 넣고 교반을 시작한다.
2.  정밀분주기로 요오드화칼륨(KIO~3~) 1 ml를 정확하게 넣고 혼합한다.
3.  50 % 황산 1ml를 넣고 혼합한다.
4.  NaI/NaOH용액 1ml를 넣고 혼합한다.
5.  MnCl~2~용액 1 ml를 넣고 혼합한다.
6.  시료병에 초순수를 채운다
7.  티오황산나튬 용액으로 종말점까지 정확하게 측정한다. 종말점이 지나지 않도록 한다. 종말점까지 사용된 티오황산나트륨 부피(V1)를 기록한다. 만약 일부 자동 적정기에서는 종말점을 지나 적정하는 것을 방지하기 어려울 경우 종말점을 V1으로 기록하고 최종적으로 첨가된 부피른 V3고 기록한다.
8.  이미 적정이 완료된 시료병에 요오드화칼륨(KIO~3~) 1 ml를 정확하게 다시 넣고 적정하여 사용된 티오황산나트륨 부피(V2)를 기록한다.

## 티오황산나트륨용액 표준화(표정) by Carpenter (1965) method

1.  티오황산나트륨의 표정은 향후 용존산소 분석을 수행할 온도와 유사한 온도조건에서 수행한다.
2.  용존산소 시료병에 초순수를 반쯤 채우고 교반자석막대를 넣어 교반기로 섞어준다.
3.  위의 용존산소 시료병에 정확히 10.0 ml 요오드산칼륨 (0.00167 M)를 옮겨 섞어준다.
4.  50% 황산 용액 1 ml를 넣고 섞어준다.
5.  알카리 요오드화나트륨(NaI/NaOH) 용액 1 ml를 넣고 잘 혼합하여 준다. 이때 요오드 이온(I^-^)은 요오드산(IO~3~^-^)에 의해 환원되어 트리아이오다이드 착물(I~3~^-^)을 형성한다 (IO~3~^-^ + 8I^-^ + 6H^+^ → 3I~3~^-^ + 3H~2~O).
6.  염화망간 1 ml를 넣고 섞어준다.
7.  초순수를 용존산소 시료병의 목부분까지 채운다\
8.  티오황산나트륨으로 적정을 실시한다. 노란 색이 거의 사라질 때 약 1 ml 녹말 지시액을 넣어준다. 이 때 용액은 반드시 진한 청색 또는 보라색을 띠어야 한다. 보라색이 사라질 때까지 적정을 한다 (I~3~^-^ + 2S~2~O~3~^2-^ → 3I^-^ + S~4~O~6~^2-^). 이 적정법에 대해서는 ± 0.03 ml 이내의 재현성을 확보해야 한다.
9.  요오드산(IO~3~^-^) 1몰은 최종적으로 티오황산염(S~2~O~3~^2-^) 6몰과 반응하게 된다. 그러므로 아래 식에 의해 적정에 사용되어진 티오황산나트륨 용액의 부피로부터 정확한 티오황산나트륨 용액의 몰농도를 간단히 구할 수 있다. 일반적으로 4번 분석한 값의 평균값을 사용하도록 한다. 종말점은 0.3%이내이어야 하고, 단위는 ml 또는 μl이고 Vstd로 기록한다.

$$C_{Na_{2}S_{2}O_{3} \cdot 5H_{2}O} = \frac{C_{KIO_3} \times 10.0 \times 6}{V_{Na_{2}S_{2}O_{3} \cdot 5H_{2}O}}$$\
$C_{Na_{2}S_{2}O_{3} \cdot 5H_{2}O} : Na_{2}S_{2}O_{3} \cdot 5H_{2}O$ 의 몰 농도 (mole/L)\
$C_{KIO_3}: KIO_3$의 몰농도 (mole/L)\
$V_{Na_{2}S_{2}O_{3} \cdot 5H_{2}O}: Na_{2}S_{2}O_{3} \cdot 5H_{2}O$의 적정부피 (mL)

## 검량선 방법(Standard-curve)에 의한 티오황산나트륨 표준화와 시약바탕 측정

1.  요오드화칼륨(KIO~3~) 2, 4, 6, 8, 10 ml를 초순수가 반쯤 채워진 각각의 용존산소병에 넣어 5개의 표준용액열을 준비한다.
2.  각 표준용액열을 적정하여 종말점을 기록한다.

## 시료분석

1.  용존산소병 목부분에 부어둔 밀봉용 초순수를 버리고 킴와이프를 사용하여 남아있는 수분을 제거한다.
2.  뚜껑을 제거하고 교반용 막대자석을 넣는다.
3.  50% 황산 1 ml를 넣고 교반기로 잘 혼합하여 침전물을 녹인다. 만약 침전물이 다 녹지 않으면 50% 황산 1 ml를 추가한다. 황산의 추가가 pH가 낮아지면 산소가 시약과 반응하여 발생하는 아이오딘(I~2~)의 생성이 더 이상 일어나지 않는다. 이는 혼합이나 적정시 용존산소병에서 발생하는 기포는 더 이상 용존산소 측정에 영향을 주지 않는다는 의미이다.
4.  티오황산나트륨 용액의 온도(t~L~)을 기록한다.
5.  시료를 종말점까지 적정하여 종말점을 기록한다. 적정부피의 단위가 ml인지 ul인지 확이하여 Vsam으로 기록한다.
6.  시료병을 세척하여 시약잔류물을 제거한다. 굳이 초수수수로 세척하지 않아도 무방하다.

## 계산

## 시약바탕값

시료에 있는 산화 또는 환원 불순물로 인해서 I~2~를 생성하기 때문에 시약바탕은 시료속에 있는 용존산소와 상관없이 나타났다.\
V~blk~ = V~1~-V~2~\
적정기가 종말점을 지나서 멈추었다면\
V~blk~ = V~1~-(V~2~-(V~3~-1)) = 2V~1~-V~2~-V~3~\
V~1~: 첫 번째 KIO3 1 ml를 적정한데 사용된 티오황산나트륨 용액의 부피\
V~2~: 첫 번째 종말점 후 추가된 KIO~3~ 1 ml를 종말점까지 적정한데 소모된 티오황산나트륨 용액의 부피\
V~3~: 첫 번째 KIO~3~ 1 ml를 적정할 때 종말점을 지났을 때 까지 사용된 티오황산나트륨 용액의 부피\
V~blk~의 단위는 ml이다.

## KIO~3~의 농도 보정

KIO~3~를 제조할 때 온도(t~p~)에서 농도를 온도가 20 ℃일 때 KIO~3~의 농도로 보정해야하고 방법은 아래와 같다.

$$M(KIO_{3}, ~ 20^{\circ} \mathrm C)= \frac {m(KIO_{3})/(213.995g \cdot mol^{-1})}{V_{s}} \times \frac{0.998206}{\rho _{w} (t_{p})}$$\
$m(KIO_{3}):$부피플라스크에 들어있는 $KIO_3$의 질량\
$V_{s}:$ $KIO_3$를 제조할 때 온도($t_{p}$)에서 용액의 부피\
$213.995g~mol^{-1} : KIO_3$ 1몰의 질량\
$\rho_{w} (t_{p}):$ 용액이 제조될 때 실험실 온도에서 물의 밀도\
$V_{s} = V_{s}[1+\alpha_{V} (t_{L} -20)]$\
$\alpha_{V}$(Pyrex유리의 부피팽창계수)$: 9.75 \times 10^{-6} ~^{\circ} K^{-1}$

## 티오황산나트륨 몰농도

실온(tL)에서 티오황산나트륨 용액의 몰농도는 아래식으로 계산한다.

$$M(Na_{2}S_{2}O_{3}, ~ t_{L})= \frac{6000 \times V(KIO_{3}, ~ t_{L}) \times M(KIO_{3}, ~ t_{L})}{V_{std} - V_{blk}}$$\
여기서,\
$V(KIO_{3}, ~ t_{L}) = V(KIO_{3}, ~ 20^{\circ} \mathrm C) \times (1+9.75 \times 10^{-6} (t_{L} -20))$\
$M(KIO_{3}, ~ t_{L}) = M(KIO_{3}, ~ 20^{\circ} \mathrm C) \times \frac{\rho_{W} (t_{L})}{0.998206}$\
$6000 = \frac{6mol~Na_{2}S_{2}O_{3}}{1mol~ KIO_{3}} \times \frac{1000 \mu l}{1ml}$\
$V_{std}$:$KIO_3$ 용액을 적정하는데 사용된 티오황산나트륨 용액의 평균부피\
$V_{blk}$: 시약바탕(reagent blank)으로 단위는 ml 또는 μl이다.

## 해수시료의 산소농도

적정된 산소 총몰수(시료+시약에 녹아있는 O~2~)는 다음 식으로 계산된다.\
$$n(O_{2})=(V_{sam}-V_{blk}) \times M(Na_{2}S_{2}O_{3}, ~ t_{L}) \times \frac{1L}{10^{6} \mu l} \times \frac{1 mol ~ O_2}{4 mol ~ Na_{2}S_{2} O_{3}}$$\
$$C(O_2)= \frac {[n(O_2)-7.6 \times 10^{-8}]}{m(sample)}$$\
여기서,\
$7.6×10^{8}$ : 시약($MnCl_2$ + $NaI/NaOH$) 2 ml에 들어 있는 용존산소($O_2$)의 양\
$m(sample)$은 해수시료의 질량(kg)으로 다음식으로 계산한다.\
$m(sample)=V(O_{2} 시료병, ~ 20^{\circ} \mathrm C) \times [1 + 9.75 \times 10^{-6} (t_s - 20)]-2 \times \rho (t_S), ~ S)$\
여기서,\
$t_S$는 시료채취시간의 온도\
2 는 첨가된 고정시약부피로 인한 해수시료 손실\
$\rho_{SW}$는 시료채취시점의 밀도

## 정도평가/정도관리(QA/QC)

자료의 정밀도를 향상시키기 위해 주기적으로 같은 채수기에서 5 ∼ 10 개 시료를 받아 분석해 보는 것이 좋다. 이 때 정밀도는 0.44 μmol/L 이하로 분석되어야 한다. 현장 정밀도는 바다날씨에 따라 0.16 ∼ 0.94 μmol/L 사이로 변할 수 있다. 용존산소 측정용 시료는 앞서 언급한 것과 같이 즉시 분석해야 정도관리에 도움이 된다.\
장기간의 분석동안 여러개의 요오드산 칼륨이 사용되었다면 동일한 티오황산나트륨 용액으로 측정한 요오드산칼륨 용액의 농도가 ±0.1 %이어야 하고, 시약바탕값의 변화를 점검하고 용존산소가 동일한 수심에서 여러개의 시료를 채취하여 분석한 정밀도가 ±0.45 μmol kg^-1^이내인지 확인한다.\
용존산소 측정용 절대 표준물질은 없다. 판매용 제품은 실험실에서 새로 만든 표준물질과 비교하는데 유용하다. 표준물질은 상대적으로 안정하므로 값이 이상할 경우 적정기의 이상으로 진단할 수 있다. 중복 시료 사이의 값의 차이가 1.78 μmol/L보다 크다면 자료를 면밀하게 검토해야 한다. 특히 심층수 값이라면 이 전의 자료와 대비시켜 보아야 한다. 적정 자료는 CTD 산소센서 자료와 비교해 볼 수 있다. CTD 산소센서 자료는 연속 자료라는 장점이 있다.

## 분석절차 흐름도