# chlorophyll a 분석 표준운영절차서

## 목적 및 범위
식물플랑크톤의 광합성 색소는 chlorophyll a, b, c 와 여러 보조색소로 구성되어 있다. 이 중 chlorophyll a 는 모든 식물플랑크톤에 포함되어 있기 때문에 식물플랑크톤의 생체량을 가장 잘 평가할 수 있는 장점이 있다. 식물플랑크톤의 현존량(생체량, 생물량)을 클로로필양으로 측정하는데는 분광광도계나 (터너) 형광분광광도계를 사용한다. 

## 측정 원리

### 분광광도계에 의한 측정
식물플랑크톤의 광합성 색소를 90 % 아세톤용액으로 추출하고 추출액의 흡광도를 750, 665, 645, 630, 480nm 에서 측정하여 chlorophyll a, b, c 및 총 카로티노이드 (total carotenoids) 량을 계산한다.
해수중 광합성 색소인 chlorophyll a 의 검출한계는 0.02μg/L이고, 그 이외 색소들의 검출 한계는 0.04μg/L 이다.
정밀도는 chlorophyll a 의 경우 5μg/L 농도수준에서 ± 0.3 μg/L, chlorophyll b 의 경우 0.5μg/L농도 수준에서 ± 0.2 μg/L이다.

### 터너 형광분광광도계에 의한 측정
이 방법은 아세톤으로 추출된 chlorophyll을 터너 형광광도계를 이용하여 측정하는 방법으로 분광광도계로 측정하는 방법보다 5~10배 감도가 높기 때문에 연안의 경우 100~200mL 정도의 시료만으로도 chlorophyll a 와 phaeo-pigment의 정량이 가능하다. 측정의 정밀도는 chlorophyll a의 농도 5 μg/L에서 ± 10 % 이내이다.

### 형광분광광도계에 의한 측정
이 방법은 아세톤으로 추출된 chlorophyll을 형광광도계를 이용하여 여기파장 (exiting wavelength) 436nm, 형광파장 (emission wavelength) 670nm 에서 형광을 측정하여 chlorophyll a 와 phaeo-pigment를 측정하는 방법이다. 측정의 정밀도는 chlorophyll a 의 농도 5μg/L에서 ± 10 % 이내이다.

## 방해물
광합성 색소인 chlorophyll a, b, c의 추출용액은 광분해가 쉽게 일어나기 때문에 여과 등의 실험과정에서 직사광선을 피해야 한다. 750nm 는 시료 중의 현탁물질에 의한 탁도 정도를 알기 위한 흡광도이다. 분광광도계의 측정 파장을 정확하게 맞추지 않으면 오차가 크게 발생한다.

## 기구 및 기기
해수중 총질소 분석에는 필요한 기구 및 기기는 여과기(4.1), 유리섬유여과지(4.2), 원심분리기(4.3), 마개 있는 원심분리관 또는 시험관 (보통 15mL)(4.4), 교반기(4.5), 분광광도계 측정법으로 분석하는 경우 분광광도계(4.6), 터너형 형광광도계 측정법으로 분석하는 경우 터너 형광광도계(4.7), 형광분광광도계 측정법으로 분석하는 경우 형광분광광도계(4.8)과 스크루 형 주사기(4.9), 스크루 형 filter holder(4.10) 등이 있다.

### 여과기
해수시료 중 식물플랑크톤을 여과지에 모으기 위한 여과기

### 유리섬유 여과지
해수시료 중 식물플랑크톤을 거르기 위한 유리섬유 여과지로 보통의 경우 GF/F, 47mm 를 사용한다.

### 원심분리기
여과지에 걸러진 엽록소 a를 아세톤 용매에 추출한 뒤 광학측정기에 사용할 상등액을 만드는 데 사용한다.

### 원심 분리관 또는 시험관
식물플랑크톤이 걸리진 여과지를 아세톤 용매에 추출하고, 상등액을 만들기 위해 원심분리하는 용기로 사용한다. 마개 있는 원심 분리관 또는 시험관으로 보통 15 mL를사용한다.

### 교반기
여과지의 식물플랑크톤 색소를 용매에 추출하기 위해 사용한다.

### 분광광도계(spectrophotometer)
분광광도계 측정법 사용시 480nm, 630nm, 645nm, 665nm, 750nm 흡광도 측정이 가능한 분광광도계로 1cm cell을 사용한다.

### 터너 형광분광광도계(Turner 10AU)
터너 형광분광광도계 측정법 사용시 터너 디자인 형광광도계에 F4T4-BL 램프, Wratten 47 B 또는 Corning CS 5-60 filter, Corning CS 2-64 filter가 있는 제품을 사용한다.

### 형광분광광도계(spectrofluorometer)
형광분광광도계 측정법 사용시 436nm 에서 여기파장(exciting wavelength), 670nm 에서 형광파장(emission wavelength) 측정이 가능한 형광분광광도계로 1cm 사각 cell을 사용한다.

### 스크루 형 주사기
분광광도법보다 적은 양의 시료 여과로 엽록소 a 측정이 가능한 형광분광광도계를 사용하는 경우 50mL 스크루 형 주사기를 시료여과에 사용한다.

### 스크루 형 filter holder
분광광보법보다 적은 양의 시료 여과로 엽록소 a 측정이 가능한 형광분광광도계를 사용하는 경우 25mm 여과지를 사용할 수 있는 스크루형 filter holder가 필요하다.

## 시약제조
엽록소 a 분석에 사용되는 시약은 아세톤(5.1), 탄산마그네슘 용액(5.2), 염산용액(5.3, 5.4), 플로레신 나트륨 용액(5.5) 등 이다. 

### 90% 아세톤(v/v)
1000mL 플라스크에 증류수 100mL와 분석용 아세톤 900mL를 넣어 만든다. 보관시에는 마개를 잘 막고 어두운 곳에 보관한다.

### 1% 탄산마그네슘 용액
탄산마그네슘(MgCO~3~) 1g을 증류수 100mL에 첨가하고 잘 흔들어 만든다.

### 1:1 염산용액
터너 형광광도계 측정시 사용하는 시약으로 진한 염산 50 mL를 증류수로 희석하여 100mL로 만든다. 

### 0.5 N 염산용액
형광분광광도계 측정시 사용하는 시약으로 진한 염산 (37%) 41mL를 증류수로 희석하여 1000mL로 만든다.

### 100 ppm 플로레신 나트륨 표준용액
형광분광광도계 측정시 사용하는 시약으로 100mg 의 플로레신 나트륨(C~20~H~10~O~4~Na~2~, sodium fluorescein)을 초순수에 녹여 1L로 만들어 냉암소에 보관한다. 이 용액은 사용직전에 홀 피펫을 사용 정확히 1mL를 취하여 100mL로 만든다. 

### 정도관리용 표준물질(Reference Material, RM)
Sigma Aldrich, Fluka 등에서 판매하는 색소 표준물질

## 시료채취 및 관리

분광광도계를 사용하는 경우, 동물플랑크톤을 제거하기 위해 약 0.3 mm 매쉬 정도의 나일론 네트를 장착시킨 여과세트에 해수시료 0.5에서 5,000 mL(해역에 따라 적당량을 취함)를 유리섬유 여과지로 여과한다.형광분광광도계를 사용하는 경우, 식물플랑크톤의 현존량이 높은 연안역이나 내만해역의 해수시료 100～200 mL를 정확히 취하여 여과기 또는 스크루형 주사기와 fiter holder를 이용하여 유리섬유여지 (GF/F, 직경 25mm)에 여과한다.  

시료를 유리섬유 여과지로 여과하는 동안 1 % 탄산마그네슘 용액 수 방울을 첨가한다. 그러나 첨가한 탄산마그네슘 용액이 시료의 산성화를 막는 완충제의 역할은 하더라도 색소파괴를 방지하는 효과가 확인되지 않아 탄산마그네슘 완충용액의 첨가는 생략하여도 무방하다.  

물기가 제거된 여과지는 15mL 시험관 또는 원심분리관에 잘 접어 넣는다.  

만일 곧바로 분석이 불가능할 경우는 빛을 차단하고 냉동보관 한다 (가능한 한 낮은 온도(-196℃ 혹은 -80℃의 낮은 온도)를 권장, 불가피 할 경우 -20℃ 가량의 일반 냉동고 사용가능). 80일 이내 분석을 권장한다.

## 시험방법

### 바탕용액의 흡광도 측정
7.1.1. 분광광도계 Cell-to-Cell Blank 보정 : 먼저 바탕용액 값은 분광광도계의 두 cell에 90 % 아세톤용액을 채우고 Reference cell에 대한 시료 cell의 Cell-to-Cell blank를 750 nm, 665 nm, 645 nm, 630 nm, 480 nm에서 흡광도를 측정하여 다음과 같이 모든 E값을 보정한다.  
$$E_{665}=OD_{665} - OD_{750}\\
E_{645}=OD_{645} - OD_{750}\\
E_{630}=OD_{630} - OD_{750}$$
여기에서 $OD$는 광학 흡광도 (optical density)임.

7.1.2. 분광광도계 표탁도 Blank의 측정 : 유리섬유여과지를 사용할 경우 빛의 흡수가 없는 것으로 알려진 파장 750 nm의 파장에서 E값을 읽는다. 이때 E값은 매우 낮으며, 이때의 Blank 값은 매우 적어 때때로 음의 값을 나타내기도 하지만 그 이유는 뚜렷하지 않다. 그 값이 음․양 어느 경우이든 ±0.002를 초과해서는 안되며, Cell-to- Cell Balnk 보정 후 모든 파장에서 E값에 사용한다.  
Membrane 여과지를 사용할 경우 소량의 콜로이드 물질이 원심분리 후에도 남는 경우가 있다. 이때 이들 물질에 의한 E값은 사용하는 파장에 따라 변하며 빛의 산란효과에 의해 파장이 짧아질 때는 증가한다. Blank 값은 750nm에서 Cell-to-Cell Blank 값으로 보정하여 얻어진 E값 (E~b~)를 아래의 f계수를 곱하면 탁도 Blank 값이 된다.  
f = 1 (파장, 666, 645, 630nm)  
f = 2 (파장, 510nm)  
f = 3 (파장, 480nm)  

따라서, 총 Blank 값은 Cell-to-Cell Blank 값과 탁도 Blank (f x Eb)를 합한 것이 된다. 식으로 표현하면 다음과 같다.  
$$Total\,Blank = (Cell-to-Cell Blank) + (f \times E_b)$$


7.1.3. 터너 형광광도계 0점 조정: 바탕용액인 90 % 아세톤으로서 형광광도계의 눈금을 0 에 맞춘다.

### 시료분석
7.2.1. 분광광도계를 사용하는 경우, 유리섬유 여과지가 끼워진 여과기에 해수시료 적당량을 따라 부으면서 여과시킨다.  
여과압은 대기압의 1/2이하(진공펌프 사용시 진공압 20mm-Hg 이하)로 하여 여과지 위에 수분이 남아 있지 않도록 한다.  
여과시 1% 탄산나트륨 용액 수 방울 (3~5방울)을 해수에 첨가한다**(하지만 생략하여도 무방하다)**.  
(터너) 형광분광광도계를 사용하는 경우, 유리섬유 여과지가 끼워진 여과기 또는 스크루형 주사기에 직경 25mm 용 스크루형 filter holder를 끼우고 해수시료 100~200mL 정도의 적당량을 따라 부으면서 여과시킨다. 여과압은 대기압의 1/2이하로 하여 여과지 위에 수분이 남아 있지 않도록 한다. 여과시 1% 탄산마그네슘 용액 수 방울 (3~5)을 해수에 첨가한다**(하지만 생략하여도 무방하다)**.
7.2.2. 수분이 제거된 여과지는 다음의 과정을 거치거나 필요시 chlorophyll 추출을 위하여 냉장보관 한다.
7.2.3. 여과지를 원심분리관 또는 시험관에 넣고 90% 아세톤 수용액을 15mL(분광광도계) 혹은 10mL(형광분광광도계)를 첨가한 후 교반기로 강하게 교반한 다음 하루동안 4℃이하의 냉암소에 보관한다.  
7.2.4. 원심분리관 또는 시험관을 실온에서 10분간 (3,000~4,000 rpm) 원심분리 시킨다.  
7.2.5. 측정  
 7.2.5.1 분광광도계: 원심분리한 후 상등액의 일부를 취하여 1cm 셀에 옮겨 750nm, 665nm, 645nm, 630nm, 480nm의 파장에서 흡광도를 측정한다.  
 7.2.5.2 터너 형광광도계: 원심분리한 시료의 상등액 일부를 취하여 측정 셀로 옮기고 시료의 형광광도계의 형광을 읽는다 (R~B~). 그리고 나서 5% 염산용액 2～3 방울을 측정 셀에 떨어뜨리고 셀을 2～3회 위 아래로 뒤집어 혼합한 다음 형광광도계에 다시 셀을 넣고 형광을 읽는다 (R~A~). 이때 라운드 셀의 형광 빛이 통과하는 부분에 이 물질이 묻지 않도록 주의한다.  
 7.2.5.3 형광분광광도계: 시료 측정을 위해서 여기파장 436nm, 형광파장 670nm에 맞춘다. 우선 원심분리한 시료 용액을 소량취하여 1cm 사각 셀에 넣고 형광를 측정한다 (F~B~). 그 다음에 0.5N 염산용액 2~3 방울을 첨가하고 혼합이 완전히 이루어져 형광이 안정될 때까지 기다린 후 형광을 측정한다 (F~A~). 염산을 첨가하지 않는 시료를 측정할 때는 이전 시료의 염산이 셀에 남아 있지 않도록 주의하여야만 하며 측정하고자하는 시료 추출 용액 1~2 mL로 셀을 1~2회 헹구어 주는 것이 좋다.

### 엽록소 농도 계산
  7.4.1. 분광광도계: 측정된 흡광도를 엽록소 농도(μg/L)로 환산한다.
$$Chlorophyll\;a, b, c (μg/L)=\frac{C_{a,b,c} \times v}{V} \times 1000$$
$Chlorophyll\;a, b, c$   : 엽록소 a, b, c의 농도 (μg/L)  
$v$   : 추출한 아세톤의 양(mL)  
$V$   : 여과한 해수의 량(mL)  
$C_a$   : 11.6 E~665~ - 1.31 E~645~ - 0.14 E~630~(엽록소 a)  
$C_b$   : 20.7 E~645~ - 4.34 E~665~ - 4.42 E~630~(엽록소 b)  
$C_c$   : 55 E~630~ - 1.31 E~665~ - 0.14 E~645~(엽록소 c)  

7.4.2. 분광광도계: 농도 계산에 사용된 모든 자료를 제시한다.  
① 표준물질 농도  
② 각 파장별 흡광도

7.4.3. 터너 형광광도계: 측정된 형광값으로 엽록소 농도(μg/L)로 환산한다.
$$Chlorophyll\;a(μg/L)=F_D\frac{r}{r-1}(R_B-R_A) \times 1000$$
$$Phaeo-pigment(μg/L)=F_D\frac{r}{r-1}(rR_A-R_B) \times 1000$$

$F_D$ : door의 계수  
$r$ : 검량선에서 얻어진 비  
$R_B$ : 산을 첨가하기 전 형광광도계의 형광을 읽은 값  
$R_A$ : 산을 첨가하고 난 후 형광광도계의 형광을 읽은 값  

 7.4.4. 형광분광광도계: 측정 흡광도로 색소 농도는 다음과 같이 계산한다.
$$Chlorophyll\;a(μg/L)=\frac{(F_B-F_A)v}{F_{ph}(R-1)V}$$
$$Phaeo-pigment(μg/L)=\frac{R(F_A-F_b)v}{F_{ph}(R-1)V}$$
$R$   :  F~ch~/F~ph~ (F~ch~ 및 F~ph~는 각각 chlorophyll a 및 phaeo-pigment 고유형광)은 순수한 chlorophyll a의  F~B~/F~A~ 값  
$v$   :  90% 아세톤으로 추출한 부피(mL)  
$V$   :  여과한 해수의 부피(mL)

### 터너 형광광도계 검량선
  7.5.1. 순수한 chlorophyll a를 얻는 것은 매우 어렵기 때문에 해양 식물플랑크톤으로부터 추출하여야만 한다. 이 방법은 전적으로 chlorophyll a만을 분석하도록 설치되어져 있지만 다른 chlorophyll에도 약간의 반응과 변화를 보인다. 이 때문에 식물플랑크톤의 종과 종과 사이에 약간의 차이가 있다. 건강하게 배양된 *Skeletonema costatum* 또는 *Skeletonema costatum*과 같은 양 (chlorophyll로서)의 *Coccolithus huxleyii* 및 *Peridinium trochoidium*로 혼합되어진 것을 chlorophyll source로 권장한다. 만약 그러한 배양을 이용할 수 없다면, phaeo-pigment 량이 불확실한 것을 제외하면 자연적인 식물플랑크톤의 개체군을 이용할 수 있다. 부영양화된 해역의 초기 “bloom" 상태(대수 생장기)인 표층수를 채수하여 이용한다.그러나 일정한 품질이 유지되는 표준시료의 확보가 어려운 경우, Sigma Aldrich, Fluka 등의 시약 제조사에서 판매하는 색소 표준물질을 활용할 수 있다.

7.5.2.충분히 배양된 또는 자연적인 개체군 50 mL를 여과하여 90%으로 추출한다. 아세톤으로 추출한 용액을 형광광도계의 door 3에서 50에 맞춘다 (R~3~). 분광광도계의 파장 정열을 주의 깊게 맞추어 chlorophyll a를 측정한 후, 다음 식으로부터 door 3에 대한 F~3~ 값을 측정한다.  
$$F_3=\frac{C_a}{R_3}$$
알고있는 chlorophyll a의 새로운 값으로서 door 10과 30에서 50 이상이 되도록 90 % 아세톤으로서 추출한 것을 희석한다. 위에서 아날로그로 표현된 것으로부터 F~10~과 F~30~을 계산한다.  

7.5.3. Door의 계수 F~D~는 7.5.1 과 7.5.2.에서 얻어진 것과 동일하고, 같은 방법으로 구하여 진다. 비 r은 phaeo-pigment가 거의 없는 것으로부터 구하여진 R~B~/R~A~ 값으로서 표준화를 위해서 사용된 추출액이다. 비 값은 2.2 가깝다.

### 형광분광광도계 조정
형광분광광도계의 감도를 ×1에 맞추고, 여기파장 (exciting wavelength) 436 nm, 형광파장 (emission wavelength) 670 nm로 맞추고 플로레신 나트륨 (C~20~H~10~O~4~Na~2~, sodium fluorescein) 표준용액 1 ppm의 형광을 100에 조정한다 (플로레신 나트륨 표준용액 0.5 ppm을 사용할 경우 여기파장 436 nm, 형광파장 515 nm에서 형광을 100이 되도록 조정한다).

## 정도평가/정도관리(QA/QC)

## 분석절차 흐름도


